//
// File generated by rootcint at Sat Feb 24 15:47:28 2018

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME CycSrimDict
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "CycSrimDict.h"

#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TInterpreter.h"
#include "TVirtualMutex.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"
#include "TFileMergeInfo.h"

// Direct notice to TROOT of the dictionary's loading.
namespace {
   static struct DictInit {
      DictInit() {
         ROOT::RegisterModule();
      }
   } __TheDictionaryInitializer;
}

// START OF SHADOWS

namespace ROOTShadow {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOTShadow
// END OF SHADOWS

namespace ROOTDict {
   void CycSrim_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void *new_CycSrim(void *p = 0);
   static void *newArray_CycSrim(Long_t size, void *p);
   static void delete_CycSrim(void *p);
   static void deleteArray_CycSrim(void *p);
   static void destruct_CycSrim(void *p);

   // Function generating the singleton type initializer
   static ROOT::TGenericClassInfo *GenerateInitInstanceLocal(const ::CycSrim*)
   {
      ::CycSrim *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::CycSrim >(0);
      static ::ROOT::TGenericClassInfo 
         instance("CycSrim", ::CycSrim::Class_Version(), "/projects/mona-sim/baumann/segmented_target/st_mona/src/../include/CycSrim.h", 87,
                  typeid(::CycSrim), ::ROOT::DefineBehavior(ptr, ptr),
                  &::CycSrim::Dictionary, isa_proxy, 4,
                  sizeof(::CycSrim) );
      instance.SetNew(&new_CycSrim);
      instance.SetNewArray(&newArray_CycSrim);
      instance.SetDelete(&delete_CycSrim);
      instance.SetDeleteArray(&deleteArray_CycSrim);
      instance.SetDestructor(&destruct_CycSrim);
      return &instance;
   }
   ROOT::TGenericClassInfo *GenerateInitInstance(const ::CycSrim*)
   {
      return GenerateInitInstanceLocal((::CycSrim*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::CycSrim*)0x0); R__UseDummy(_R__UNIQUE_(Init));
} // end of namespace ROOTDict

//______________________________________________________________________________
atomic_TClass_ptr CycSrim::fgIsA(0);  // static to hold class pointer

//______________________________________________________________________________
const char *CycSrim::Class_Name()
{
   return "CycSrim";
}

//______________________________________________________________________________
const char *CycSrim::ImplFileName()
{
   return ::ROOTDict::GenerateInitInstanceLocal((const ::CycSrim*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int CycSrim::ImplFileLine()
{
   return ::ROOTDict::GenerateInitInstanceLocal((const ::CycSrim*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void CycSrim::Dictionary()
{
   fgIsA = ::ROOTDict::GenerateInitInstanceLocal((const ::CycSrim*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *CycSrim::Class()
{
   if (!fgIsA) { R__LOCKGUARD2(gCINTMutex); if(!fgIsA) {fgIsA = ::ROOTDict::GenerateInitInstanceLocal((const ::CycSrim*)0x0)->GetClass();} }
   return fgIsA;
}

//______________________________________________________________________________
void CycSrim::Streamer(TBuffer &R__b)
{
   // Stream an object of class CycSrim.

   if (R__b.IsReading()) {
      R__b.ReadClassBuffer(CycSrim::Class(),this);
   } else {
      R__b.WriteClassBuffer(CycSrim::Class(),this);
   }
}

//______________________________________________________________________________
void CycSrim::ShowMembers(TMemberInspector &R__insp)
{
      // Inspect the data members of an object of class CycSrim.
      TClass *R__cl = ::CycSrim::IsA();
      if (R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fStopping[92][200][7]", fStopping);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fNumStopping[92]", fNumStopping);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fMaterialName", &fMaterialName);
      R__insp.InspectMember(fMaterialName, "fMaterialName.");
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fMaterialDensity", &fMaterialDensity);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fMaterialFactor", &fMaterialFactor);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fNumMaterials", &fNumMaterials);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fMaterialComposition[10][3]", fMaterialComposition);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fMaterial", &fMaterial);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fThickness", &fThickness);
}

namespace ROOTDict {
   // Wrappers around operator new
   static void *new_CycSrim(void *p) {
      return  p ? ::new((::ROOT::TOperatorNewHelper*)p) ::CycSrim : new ::CycSrim;
   }
   static void *newArray_CycSrim(Long_t nElements, void *p) {
      return p ? ::new((::ROOT::TOperatorNewHelper*)p) ::CycSrim[nElements] : new ::CycSrim[nElements];
   }
   // Wrapper around operator delete
   static void delete_CycSrim(void *p) {
      delete ((::CycSrim*)p);
   }
   static void deleteArray_CycSrim(void *p) {
      delete [] ((::CycSrim*)p);
   }
   static void destruct_CycSrim(void *p) {
      typedef ::CycSrim current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOTDict for class ::CycSrim

/********************************************************
* CycSrimDict.cxx
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtableCycSrimDict();

extern "C" void G__set_cpp_environmentCycSrimDict() {
  G__cpp_reset_tagtableCycSrimDict();
}
#include <new>
extern "C" int G__cpp_dllrevCycSrimDict() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* CycSrim */
static int G__CycSrimDict_505_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   CycSrim* p = NULL;
   char* gvp = (char*) G__getgvp();
   int n = G__getaryconstruct();
   if (n) {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new CycSrim[n];
     } else {
       p = new((void*) gvp) CycSrim[n];
     }
   } else {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new CycSrim;
     } else {
       p = new((void*) gvp) CycSrim;
     }
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__CycSrimDictLN_CycSrim));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__CycSrimDict_505_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   CycSrim* p = NULL;
   char* gvp = (char*) G__getgvp();
   switch (libp->paran) {
   case 3:
     //m: 3
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new CycSrim(
(Int_t) G__int(libp->para[0]), (Double_t) G__double(libp->para[1])
, (CycSrim::srimDensityUnits) G__int(libp->para[2]));
     } else {
       p = new((void*) gvp) CycSrim(
(Int_t) G__int(libp->para[0]), (Double_t) G__double(libp->para[1])
, (CycSrim::srimDensityUnits) G__int(libp->para[2]));
     }
     break;
   case 2:
     //m: 2
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new CycSrim((Int_t) G__int(libp->para[0]), (Double_t) G__double(libp->para[1]));
     } else {
       p = new((void*) gvp) CycSrim((Int_t) G__int(libp->para[0]), (Double_t) G__double(libp->para[1]));
     }
     break;
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__CycSrimDictLN_CycSrim));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__CycSrimDict_505_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   CycSrim* p = NULL;
   char* gvp = (char*) G__getgvp();
   switch (libp->paran) {
   case 4:
     //m: 4
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new CycSrim(
(Int_t) G__int(libp->para[0]), (Double_t) G__double(libp->para[1])
, (Double_t) G__double(libp->para[2]), (CycSrim::srimDensityUnits) G__int(libp->para[3]));
     } else {
       p = new((void*) gvp) CycSrim(
(Int_t) G__int(libp->para[0]), (Double_t) G__double(libp->para[1])
, (Double_t) G__double(libp->para[2]), (CycSrim::srimDensityUnits) G__int(libp->para[3]));
     }
     break;
   case 3:
     //m: 3
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new CycSrim(
(Int_t) G__int(libp->para[0]), (Double_t) G__double(libp->para[1])
, (Double_t) G__double(libp->para[2]));
     } else {
       p = new((void*) gvp) CycSrim(
(Int_t) G__int(libp->para[0]), (Double_t) G__double(libp->para[1])
, (Double_t) G__double(libp->para[2]));
     }
     break;
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__CycSrimDictLN_CycSrim));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__CycSrimDict_505_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((CycSrim*) G__getstructoffset())->GetEnergyLoss((Int_t) G__int(libp->para[0]), (Double_t) G__double(libp->para[1])
, (Double_t) G__double(libp->para[2])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__CycSrimDict_505_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((CycSrim*) G__getstructoffset())->GetEnergyLossFromResidual((Int_t) G__int(libp->para[0]), (Double_t) G__double(libp->para[1])
, (Double_t) G__double(libp->para[2])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__CycSrimDict_505_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((CycSrim*) G__getstructoffset())->GetResidualEnergy((Int_t) G__int(libp->para[0]), (Double_t) G__double(libp->para[1])
, (Double_t) G__double(libp->para[2])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__CycSrimDict_505_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((CycSrim*) G__getstructoffset())->GetResidualEnergyFromDe((Int_t) G__int(libp->para[0]), (Double_t) G__double(libp->para[1])
, (Double_t) G__double(libp->para[2])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__CycSrimDict_505_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((CycSrim*) G__getstructoffset())->GetIncidentEnergy((Int_t) G__int(libp->para[0]), (Double_t) G__double(libp->para[1])
, (Double_t) G__double(libp->para[2])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__CycSrimDict_505_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 4:
      G__letdouble(result7, 100, (double) ((CycSrim*) G__getstructoffset())->GetRange((Int_t) G__int(libp->para[0]), (Double_t) G__double(libp->para[1])
, (Double_t) G__double(libp->para[2]), (Bool_t) G__int(libp->para[3])));
      break;
   case 3:
      G__letdouble(result7, 100, (double) ((CycSrim*) G__getstructoffset())->GetRange((Int_t) G__int(libp->para[0]), (Double_t) G__double(libp->para[1])
, (Double_t) G__double(libp->para[2])));
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__CycSrimDict_505_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((CycSrim*) G__getstructoffset())->GetDeDx((Int_t) G__int(libp->para[0]), (Double_t) G__double(libp->para[1])
, (Double_t) G__double(libp->para[2])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__CycSrimDict_505_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((CycSrim*) G__getstructoffset())->GetDeDxElectronic((Int_t) G__int(libp->para[0]), (Double_t) G__double(libp->para[1])
, (Double_t) G__double(libp->para[2])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__CycSrimDict_505_0_12(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((CycSrim*) G__getstructoffset())->GetDeDxNuclear((Int_t) G__int(libp->para[0]), (Double_t) G__double(libp->para[1])
, (Double_t) G__double(libp->para[2])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__CycSrimDict_505_0_13(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((CycSrim*) G__getstructoffset())->TestInterp((Int_t) G__int(libp->para[0]), libp->para[1].ref ? *(TGraph**) libp->para[1].ref : *(TGraph**) (void*) (&G__Mlong(libp->para[1]))
, libp->para[2].ref ? *(TGraph**) libp->para[2].ref : *(TGraph**) (void*) (&G__Mlong(libp->para[2])));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__CycSrimDict_505_0_14(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((const CycSrim*) G__getstructoffset())->GetThickness());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__CycSrimDict_505_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((CycSrim*) G__getstructoffset())->SetThickness((Double_t) G__double(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__CycSrimDict_505_0_16(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((CycSrim*) G__getstructoffset())->GetPunchthroughEnergy((Int_t) G__int(libp->para[0]), (Double_t) G__double(libp->para[1])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__CycSrimDict_505_0_21(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) CycSrim::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__CycSrimDict_505_0_22(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) CycSrim::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__CycSrimDict_505_0_23(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) CycSrim::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__CycSrimDict_505_0_24(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      CycSrim::Dictionary();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__CycSrimDict_505_0_25(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) ((const CycSrim*) G__getstructoffset())->IsA());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__CycSrimDict_505_0_26(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((CycSrim*) G__getstructoffset())->ShowMembers(*(TMemberInspector*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__CycSrimDict_505_0_27(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((CycSrim*) G__getstructoffset())->Streamer(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__CycSrimDict_505_0_28(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((CycSrim*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__CycSrimDict_505_0_29(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) CycSrim::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__CycSrimDict_505_0_30(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) CycSrim::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__CycSrimDict_505_0_31(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) CycSrim::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__CycSrimDict_505_0_32(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) CycSrim::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__CycSrimDict_505_0_33(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   CycSrim* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new CycSrim(*(CycSrim*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__CycSrimDictLN_CycSrim));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef CycSrim G__TCycSrim;
static int G__CycSrimDict_505_0_34(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 0
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (CycSrim*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((CycSrim*) (soff+(sizeof(CycSrim)*i)))->~G__TCycSrim();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (CycSrim*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((CycSrim*) (soff))->~G__TCycSrim();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G__CycSrimDict_505_0_35(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   CycSrim* dest = (CycSrim*) G__getstructoffset();
   *dest = *(CycSrim*) libp->para[0].ref;
   const CycSrim& obj = *dest;
   result7->ref = (long) (&obj);
   result7->obj.i = (long) (&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* CycSrim */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncCycSrimDict {
 public:
  G__Sizep2memfuncCycSrimDict(): p(&G__Sizep2memfuncCycSrimDict::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncCycSrimDict::*p)();
};

size_t G__get_sizep2memfuncCycSrimDict()
{
  G__Sizep2memfuncCycSrimDict a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritanceCycSrimDict() {

   /* Setting up class inheritance */
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetableCycSrimDict() {

   /* Setting up typedef entry */
   G__search_typename2("Int_t",105,-1,0,-1);
   G__setnewtype(-1,"Signed integer 4 bytes (int)",0);
   G__search_typename2("Double_t",100,-1,0,-1);
   G__setnewtype(-1,"Double 8 bytes",0);
   G__search_typename2("Bool_t",103,-1,0,-1);
   G__setnewtype(-1,"Boolean (0=false, 1=true) (bool)",0);
   G__search_typename2("Version_t",115,-1,0,-1);
   G__setnewtype(-1,"Class version identifier (short)",0);
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__CycSrimDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__CycSrimDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__CycSrimDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__CycSrimDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__CycSrimDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__CycSrimDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__CycSrimDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__CycSrimDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__CycSrimDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__CycSrimDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<std::bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__CycSrimDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__CycSrimDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*>",117,G__get_linked_tagnum(&G__CycSrimDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long>",117,G__get_linked_tagnum(&G__CycSrimDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long,const TObject**>",117,G__get_linked_tagnum(&G__CycSrimDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<Int_t,TGeoElementRN*>",117,G__get_linked_tagnum(&G__CycSrimDictLN_maplEintcOTGeoElementRNmUcOlesslEintgRcOallocatorlEpairlEconstsPintcOTGeoElementRNmUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<int,TGeoElementRN*>",117,G__get_linked_tagnum(&G__CycSrimDictLN_maplEintcOTGeoElementRNmUcOlesslEintgRcOallocatorlEpairlEconstsPintcOTGeoElementRNmUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<int,TGeoElementRN*,less<int> >",117,G__get_linked_tagnum(&G__CycSrimDictLN_maplEintcOTGeoElementRNmUcOlesslEintgRcOallocatorlEpairlEconstsPintcOTGeoElementRNmUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<ThreadData_t*>",117,G__get_linked_tagnum(&G__CycSrimDictLN_vectorlETGeoVolumeAssemblycLcLThreadData_tmUcOallocatorlETGeoVolumeAssemblycLcLThreadData_tmUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__CycSrimDictLN_reverse_iteratorlEvectorlETGeoVolumeAssemblycLcLThreadData_tmUcOallocatorlETGeoVolumeAssemblycLcLThreadData_tmUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__CycSrimDictLN_vectorlETGeoVolumeAssemblycLcLThreadData_tmUcOallocatorlETGeoVolumeAssemblycLcLThreadData_tmUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__CycSrimDictLN_reverse_iteratorlEvectorlETGeoVolumeAssemblycLcLThreadData_tmUcOallocatorlETGeoVolumeAssemblycLcLThreadData_tmUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__CycSrimDictLN_vectorlETGeoVolumeAssemblycLcLThreadData_tmUcOallocatorlETGeoVolumeAssemblycLcLThreadData_tmUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TGeoVolumeAssembly::ThreadData_t*>",117,G__get_linked_tagnum(&G__CycSrimDictLN_vectorlETGeoVolumeAssemblycLcLThreadData_tmUcOallocatorlETGeoVolumeAssemblycLcLThreadData_tmUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<Long_t,TGeoNavigatorArray*>",117,G__get_linked_tagnum(&G__CycSrimDictLN_maplElongcOTGeoNavigatorArraymUcOlesslElonggRcOallocatorlEpairlEconstsPlongcOTGeoNavigatorArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<long,TGeoNavigatorArray*>",117,G__get_linked_tagnum(&G__CycSrimDictLN_maplElongcOTGeoNavigatorArraymUcOlesslElonggRcOallocatorlEpairlEconstsPlongcOTGeoNavigatorArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<long,TGeoNavigatorArray*,less<long> >",117,G__get_linked_tagnum(&G__CycSrimDictLN_maplElongcOTGeoNavigatorArraymUcOlesslElonggRcOallocatorlEpairlEconstsPlongcOTGeoNavigatorArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<Long_t,Int_t>",117,G__get_linked_tagnum(&G__CycSrimDictLN_maplElongcOintcOlesslElonggRcOallocatorlEpairlEconstsPlongcOintgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* CycSrim */
static void G__setup_memvarCycSrim(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__CycSrimDictLN_CycSrim));
   { CycSrim *p; p=(CycSrim*)0x1000; if (p) { }
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__CycSrimDictLN_CycSrimcLcLsrimDensityUnits),-1,-2,1,G__FastAllocString(2048).Format("kUnitsMgCm2=%lldLL",(long long)CycSrim::kUnitsMgCm2).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__CycSrimDictLN_CycSrimcLcLsrimDensityUnits),-1,-2,1,G__FastAllocString(2048).Format("kUnitsCm=%lldLL",(long long)CycSrim::kUnitsCm).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__CycSrimDictLN_CycSrimcLcLsrimDensityUnits),-1,-2,1,G__FastAllocString(2048).Format("kUnitsMicron=%lldLL",(long long)CycSrim::kUnitsMicron).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__CycSrimDictLN_CycSrimcLcLsrimDensityUnits),-1,-2,1,G__FastAllocString(2048).Format("kUnitsTorr=%lldLL",(long long)CycSrim::kUnitsTorr).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__CycSrimDictLN_CycSrimcLcLsrimDensityUnits),-1,-2,1,G__FastAllocString(2048).Format("kUnitsMbar=%lldLL",(long long)CycSrim::kUnitsMbar).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__CycSrimDictLN_CycSrimcLcLEMaterials),-1,-2,1,G__FastAllocString(2048).Format("SrimMaterialSi=%lldLL",(long long)CycSrim::SrimMaterialSi).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__CycSrimDictLN_CycSrimcLcLEMaterials),-1,-2,1,G__FastAllocString(2048).Format("SrimMaterialMylar=%lldLL",(long long)CycSrim::SrimMaterialMylar).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__CycSrimDictLN_CycSrimcLcLEMaterials),-1,-2,1,G__FastAllocString(2048).Format("SrimMaterialIsobutane=%lldLL",(long long)CycSrim::SrimMaterialIsobutane).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__CycSrimDictLN_CycSrimcLcLEMaterials),-1,-2,1,G__FastAllocString(2048).Format("SrimMaterialPentane=%lldLL",(long long)CycSrim::SrimMaterialPentane).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__CycSrimDictLN_CycSrimcLcLEMaterials),-1,-2,1,G__FastAllocString(2048).Format("SrimMaterialAluminum=%lldLL",(long long)CycSrim::SrimMaterialAluminum).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__CycSrimDictLN_CycSrimcLcLEMaterials),-1,-2,1,G__FastAllocString(2048).Format("SrimMaterialNickel=%lldLL",(long long)CycSrim::SrimMaterialNickel).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__CycSrimDictLN_CycSrimcLcLEMaterials),-1,-2,1,G__FastAllocString(2048).Format("SrimMaterialBC420=%lldLL",(long long)CycSrim::SrimMaterialBC420).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__CycSrimDictLN_CycSrimcLcLEMaterials),-1,-2,1,G__FastAllocString(2048).Format("SrimMaterialCsI=%lldLL",(long long)CycSrim::SrimMaterialCsI).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__CycSrimDictLN_CycSrimcLcLEMaterials),-1,-2,1,G__FastAllocString(2048).Format("SrimMaterialCarbon=%lldLL",(long long)CycSrim::SrimMaterialCarbon).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__CycSrimDictLN_CycSrimcLcLEMaterials),-1,-2,1,G__FastAllocString(2048).Format("SrimMaterialAu=%lldLL",(long long)CycSrim::SrimMaterialAu).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__CycSrimDictLN_CycSrimcLcLEMaterials),-1,-2,1,G__FastAllocString(2048).Format("SrimMaterialPolypropylene=%lldLL",(long long)CycSrim::SrimMaterialPolypropylene).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__CycSrimDictLN_CycSrimcLcLEMaterials),-1,-2,1,G__FastAllocString(2048).Format("SrimMaterialLowDensityPolyethylene=%lldLL",(long long)CycSrim::SrimMaterialLowDensityPolyethylene).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__CycSrimDictLN_CycSrimcLcLEMaterials),-1,-2,1,G__FastAllocString(2048).Format("SrimMaterialTh=%lldLL",(long long)CycSrim::SrimMaterialTh).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__CycSrimDictLN_CycSrimcLcLEMaterials),-1,-2,1,G__FastAllocString(2048).Format("SrimMaterialBeryllium=%lldLL",(long long)CycSrim::SrimMaterialBeryllium).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__CycSrimDictLN_CycSrimcLcLEMaterials),-1,-2,1,G__FastAllocString(2048).Format("SrimMaterialDeuterium=%lldLL",(long long)CycSrim::SrimMaterialDeuterium).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__CycSrimDictLN_CycSrimcLcLEMaterials),-1,-2,1,G__FastAllocString(2048).Format("SrimMaterialKapton=%lldLL",(long long)CycSrim::SrimMaterialKapton).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__CycSrimDictLN_CycSrimcLcLEMaterials),-1,-2,1,G__FastAllocString(2048).Format("SrimNumberOfMaterials=%lldLL",(long long)CycSrim::SrimNumberOfMaterials).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__CycSrimDictLN_CycSrimcLcLEMaterials),-1,-2,1,G__FastAllocString(2048).Format("SrimMaxNumberOfEnergies=%lldLL",(long long)CycSrim::SrimMaxNumberOfEnergies).data(),0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,G__defined_typename("Double_t"),-1,4,"fStopping[92][200][7]=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,G__defined_typename("Int_t"),-1,4,"fNumStopping[92]=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__CycSrimDictLN_TString),-1,-1,4,"fMaterialName=",0,(char*)NULL);
   G__memvar_setup((void*)0,102,0,0,-1,G__defined_typename("Float_t"),-1,4,"fMaterialDensity=",0,(char*)NULL);
   G__memvar_setup((void*)0,102,0,0,-1,G__defined_typename("Float_t"),-1,4,"fMaterialFactor=",0,"factor to go from thickness in units specified to mg/cm^2");
   G__memvar_setup((void*)0,105,0,0,-1,G__defined_typename("Int_t"),-1,4,"fNumMaterials=",0,(char*)NULL);
   G__memvar_setup((void*)0,102,0,0,-1,G__defined_typename("Float_t"),-1,4,"fMaterialComposition[10][3]=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,G__defined_typename("Int_t"),-1,4,"fMaterial=",0,"Material number");
   G__memvar_setup((void*)0,100,0,0,-1,G__defined_typename("Double_t"),-1,4,"fThickness=",0,"Thickness in mg/cm2");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__CycSrimDictLN_TClass),G__defined_typename("atomic_TClass_ptr"),-2,4,"fgIsA=",0,(char*)NULL);
   G__memvar_setup((void*)0,108,0,0,-1,-1,-1,4,"G__virtualinfo=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarCycSrimDict() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncCycSrim(void) {
   /* CycSrim */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__CycSrimDictLN_CycSrim));
   G__memfunc_setup("CycSrim",698,G__CycSrimDict_505_0_1, 105, G__get_linked_tagnum(&G__CycSrimDictLN_CycSrim), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("CycSrim",698,G__CycSrimDict_505_0_2, 105, G__get_linked_tagnum(&G__CycSrimDictLN_CycSrim), -1, 0, 3, 1, 1, 0, 
"i - 'Int_t' 0 - imat d - 'Double_t' 0 - thickness "
"i 'CycSrim::srimDensityUnits' - 0 'kUnitsMgCm2' units", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("CycSrim",698,G__CycSrimDict_505_0_3, 105, G__get_linked_tagnum(&G__CycSrimDictLN_CycSrim), -1, 0, 4, 1, 1, 0, 
"i - 'Int_t' 0 - imat d - 'Double_t' 0 - thickness "
"d - 'Double_t' 0 - pressure i 'CycSrim::srimDensityUnits' - 0 'kUnitsTorr' units", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetEnergyLoss",1323,G__CycSrimDict_505_0_4, 100, -1, G__defined_typename("Double_t"), 0, 3, 1, 1, 0, 
"i - 'Int_t' 0 - z d - 'Double_t' 0 - m "
"d - 'Double_t' 0 - etot", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetEnergyLossFromResidual",2552,G__CycSrimDict_505_0_5, 100, -1, G__defined_typename("Double_t"), 0, 3, 1, 1, 0, 
"i - 'Int_t' 0 - z d - 'Double_t' 0 - a "
"d - 'Double_t' 0 - eres", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetResidualEnergy",1731,G__CycSrimDict_505_0_6, 100, -1, G__defined_typename("Double_t"), 0, 3, 1, 1, 0, 
"i - 'Int_t' 0 - z d - 'Double_t' 0 - m "
"d - 'Double_t' 0 - etot", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetResidualEnergyFromDe",2304,G__CycSrimDict_505_0_7, 100, -1, G__defined_typename("Double_t"), 0, 3, 1, 1, 0, 
"i - 'Int_t' 0 - z d - 'Double_t' 0 - a "
"d - 'Double_t' 0 - de", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetIncidentEnergy",1720,G__CycSrimDict_505_0_8, 100, -1, G__defined_typename("Double_t"), 0, 3, 1, 1, 0, 
"i - 'Int_t' 0 - z d - 'Double_t' 0 - m "
"d - 'Double_t' 0 - de", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetRange",781,G__CycSrimDict_505_0_9, 100, -1, G__defined_typename("Double_t"), 0, 4, 1, 1, 0, 
"i - 'Int_t' 0 - z d - 'Double_t' 0 - m "
"d - 'Double_t' 0 - etot g - 'Bool_t' 0 'kTRUE' lengthUnits", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetDeDx",645,G__CycSrimDict_505_0_10, 100, -1, G__defined_typename("Double_t"), 0, 3, 1, 1, 0, 
"i - 'Int_t' 0 - z d - 'Double_t' 0 - m "
"d - 'Double_t' 0 - etot", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetDeDxElectronic",1677,G__CycSrimDict_505_0_11, 100, -1, G__defined_typename("Double_t"), 0, 3, 1, 1, 0, 
"i - 'Int_t' 0 - z d - 'Double_t' 0 - m "
"d - 'Double_t' 0 - etot", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetDeDxNuclear",1359,G__CycSrimDict_505_0_12, 100, -1, G__defined_typename("Double_t"), 0, 3, 1, 1, 0, 
"i - 'Int_t' 0 - z d - 'Double_t' 0 - m "
"d - 'Double_t' 0 - etot", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("TestInterp",1042,G__CycSrimDict_505_0_13, 121, -1, -1, 0, 3, 1, 1, 0, 
"i - 'Int_t' 0 - z U 'TGraph' - 1 - grData "
"U 'TGraph' - 1 - grInterp", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetThickness",1228,G__CycSrimDict_505_0_14, 100, -1, G__defined_typename("Double_t"), 0, 0, 1, 1, 8, "", "return in mg/cm^2", (void*) NULL, 0);
   G__memfunc_setup("SetThickness",1240,G__CycSrimDict_505_0_15, 100, -1, G__defined_typename("Double_t"), 0, 1, 1, 1, 0, "d - 'Double_t' 0 - thick", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetPunchthroughEnergy",2185,G__CycSrimDict_505_0_16, 100, -1, G__defined_typename("Double_t"), 0, 2, 1, 1, 0, 
"i - 'Int_t' 0 - z d - 'Double_t' 0 - m", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Init",404,(G__InterfaceMethod) NULL, 105, -1, -1, 0, 0, 1, 4, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetSrimDataDir",1364,(G__InterfaceMethod) NULL, 67, -1, G__defined_typename("Char_t"), 0, 0, 1, 4, 9, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Interp",626,(G__InterfaceMethod) NULL, 100, -1, G__defined_typename("Double_t"), 0, 5, 1, 4, 0, 
"D - 'Double_t' 10 - x D - 'Double_t' 10 - y "
"i - 'Int_t' 0 - ntps i - 'Int_t' 0 - nterms "
"d - 'Double_t' 0 - xin", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Intero",625,(G__InterfaceMethod) NULL, 100, -1, G__defined_typename("Double_t"), 0, 5, 1, 4, 0, 
"D - 'Double_t' 10 - x D - 'Double_t' 10 - y "
"i - 'Int_t' 0 - ntps i - 'Int_t' 0 - nterms "
"d - 'Double_t' 0 - xin", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Class",502,G__CycSrimDict_505_0_21, 85, G__get_linked_tagnum(&G__CycSrimDictLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (TClass* (*)())(&CycSrim::Class) ), 0);
   G__memfunc_setup("Class_Name",982,G__CycSrimDict_505_0_22, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&CycSrim::Class_Name) ), 0);
   G__memfunc_setup("Class_Version",1339,G__CycSrimDict_505_0_23, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (Version_t (*)())(&CycSrim::Class_Version) ), 0);
   G__memfunc_setup("Dictionary",1046,G__CycSrimDict_505_0_24, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (void (*)())(&CycSrim::Dictionary) ), 0);
   G__memfunc_setup("IsA",253,G__CycSrimDict_505_0_25, 85, G__get_linked_tagnum(&G__CycSrimDictLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ShowMembers",1132,G__CycSrimDict_505_0_26, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TMemberInspector' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Streamer",835,G__CycSrimDict_505_0_27, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("StreamerNVirtual",1656,G__CycSrimDict_505_0_28, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - ClassDef_StreamerNVirtual_b", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DeclFileName",1145,G__CycSrimDict_505_0_29, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&CycSrim::DeclFileName) ), 0);
   G__memfunc_setup("ImplFileLine",1178,G__CycSrimDict_505_0_30, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&CycSrim::ImplFileLine) ), 0);
   G__memfunc_setup("ImplFileName",1171,G__CycSrimDict_505_0_31, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&CycSrim::ImplFileName) ), 0);
   G__memfunc_setup("DeclFileLine",1152,G__CycSrimDict_505_0_32, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&CycSrim::DeclFileLine) ), 0);
   // automatic copy constructor
   G__memfunc_setup("CycSrim", 698, G__CycSrimDict_505_0_33, (int) ('i'), G__get_linked_tagnum(&G__CycSrimDictLN_CycSrim), -1, 0, 1, 1, 1, 0, "u 'CycSrim' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~CycSrim", 824, G__CycSrimDict_505_0_34, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 0);
   // automatic assignment operator
   G__memfunc_setup("operator=", 937, G__CycSrimDict_505_0_35, (int) ('u'), G__get_linked_tagnum(&G__CycSrimDictLN_CycSrim), -1, 1, 1, 1, 1, 0, "u 'CycSrim' - 11 - -", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncCycSrimDict() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalCycSrimDict() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {
}

static void G__cpp_setup_func13() {
}

static void G__cpp_setup_func14() {
}

static void G__cpp_setup_func15() {
}

static void G__cpp_setup_func16() {
}

static void G__cpp_setup_func17() {
}

static void G__cpp_setup_func18() {
}

static void G__cpp_setup_func19() {
}

static void G__cpp_setup_func20() {
}

static void G__cpp_setup_func21() {
}

static void G__cpp_setup_func22() {
}

static void G__cpp_setup_func23() {
}

static void G__cpp_setup_func24() {
}

static void G__cpp_setup_func25() {
}

static void G__cpp_setup_func26() {
}

static void G__cpp_setup_func27() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcCycSrimDict() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
  G__cpp_setup_func13();
  G__cpp_setup_func14();
  G__cpp_setup_func15();
  G__cpp_setup_func16();
  G__cpp_setup_func17();
  G__cpp_setup_func18();
  G__cpp_setup_func19();
  G__cpp_setup_func20();
  G__cpp_setup_func21();
  G__cpp_setup_func22();
  G__cpp_setup_func23();
  G__cpp_setup_func24();
  G__cpp_setup_func25();
  G__cpp_setup_func26();
  G__cpp_setup_func27();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__CycSrimDictLN_TClass = { "TClass" , 99 , -1 };
G__linked_taginfo G__CycSrimDictLN_TBuffer = { "TBuffer" , 99 , -1 };
G__linked_taginfo G__CycSrimDictLN_TMemberInspector = { "TMemberInspector" , 99 , -1 };
G__linked_taginfo G__CycSrimDictLN_TString = { "TString" , 99 , -1 };
G__linked_taginfo G__CycSrimDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__CycSrimDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__CycSrimDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G__CycSrimDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__CycSrimDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR = { "iterator<bidirectional_iterator_tag,TObject*,long,const TObject**,const TObject*&>" , 115 , -1 };
G__linked_taginfo G__CycSrimDictLN_maplElongcOintcOlesslElonggRcOallocatorlEpairlEconstsPlongcOintgRsPgRsPgR = { "map<long,int,less<long>,allocator<pair<const long,int> > >" , 99 , -1 };
G__linked_taginfo G__CycSrimDictLN_maplEintcOTGeoElementRNmUcOlesslEintgRcOallocatorlEpairlEconstsPintcOTGeoElementRNmUgRsPgRsPgR = { "map<int,TGeoElementRN*,less<int>,allocator<pair<const int,TGeoElementRN*> > >" , 99 , -1 };
G__linked_taginfo G__CycSrimDictLN_vectorlETGeoVolumeAssemblycLcLThreadData_tmUcOallocatorlETGeoVolumeAssemblycLcLThreadData_tmUgRsPgR = { "vector<TGeoVolumeAssembly::ThreadData_t*,allocator<TGeoVolumeAssembly::ThreadData_t*> >" , 99 , -1 };
G__linked_taginfo G__CycSrimDictLN_reverse_iteratorlEvectorlETGeoVolumeAssemblycLcLThreadData_tmUcOallocatorlETGeoVolumeAssemblycLcLThreadData_tmUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TGeoVolumeAssembly::ThreadData_t*,allocator<TGeoVolumeAssembly::ThreadData_t*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__CycSrimDictLN_maplElongcOTGeoNavigatorArraymUcOlesslElonggRcOallocatorlEpairlEconstsPlongcOTGeoNavigatorArraymUgRsPgRsPgR = { "map<long,TGeoNavigatorArray*,less<long>,allocator<pair<const long,TGeoNavigatorArray*> > >" , 99 , -1 };
G__linked_taginfo G__CycSrimDictLN_TGraph = { "TGraph" , 99 , -1 };
G__linked_taginfo G__CycSrimDictLN_CycSrim = { "CycSrim" , 99 , -1 };
G__linked_taginfo G__CycSrimDictLN_CycSrimcLcLsrimDensityUnits = { "CycSrim::srimDensityUnits" , 101 , -1 };
G__linked_taginfo G__CycSrimDictLN_CycSrimcLcLEMaterials = { "CycSrim::EMaterials" , 101 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtableCycSrimDict() {
  G__CycSrimDictLN_TClass.tagnum = -1 ;
  G__CycSrimDictLN_TBuffer.tagnum = -1 ;
  G__CycSrimDictLN_TMemberInspector.tagnum = -1 ;
  G__CycSrimDictLN_TString.tagnum = -1 ;
  G__CycSrimDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__CycSrimDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__CycSrimDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G__CycSrimDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__CycSrimDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR.tagnum = -1 ;
  G__CycSrimDictLN_maplElongcOintcOlesslElonggRcOallocatorlEpairlEconstsPlongcOintgRsPgRsPgR.tagnum = -1 ;
  G__CycSrimDictLN_maplEintcOTGeoElementRNmUcOlesslEintgRcOallocatorlEpairlEconstsPintcOTGeoElementRNmUgRsPgRsPgR.tagnum = -1 ;
  G__CycSrimDictLN_vectorlETGeoVolumeAssemblycLcLThreadData_tmUcOallocatorlETGeoVolumeAssemblycLcLThreadData_tmUgRsPgR.tagnum = -1 ;
  G__CycSrimDictLN_reverse_iteratorlEvectorlETGeoVolumeAssemblycLcLThreadData_tmUcOallocatorlETGeoVolumeAssemblycLcLThreadData_tmUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__CycSrimDictLN_maplElongcOTGeoNavigatorArraymUcOlesslElonggRcOallocatorlEpairlEconstsPlongcOTGeoNavigatorArraymUgRsPgRsPgR.tagnum = -1 ;
  G__CycSrimDictLN_TGraph.tagnum = -1 ;
  G__CycSrimDictLN_CycSrim.tagnum = -1 ;
  G__CycSrimDictLN_CycSrimcLcLsrimDensityUnits.tagnum = -1 ;
  G__CycSrimDictLN_CycSrimcLcLEMaterials.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtableCycSrimDict() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__CycSrimDictLN_TClass);
   G__get_linked_tagnum_fwd(&G__CycSrimDictLN_TBuffer);
   G__get_linked_tagnum_fwd(&G__CycSrimDictLN_TMemberInspector);
   G__get_linked_tagnum_fwd(&G__CycSrimDictLN_TString);
   G__get_linked_tagnum_fwd(&G__CycSrimDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__CycSrimDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__CycSrimDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G__CycSrimDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__CycSrimDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR);
   G__get_linked_tagnum_fwd(&G__CycSrimDictLN_maplElongcOintcOlesslElonggRcOallocatorlEpairlEconstsPlongcOintgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__CycSrimDictLN_maplEintcOTGeoElementRNmUcOlesslEintgRcOallocatorlEpairlEconstsPintcOTGeoElementRNmUgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__CycSrimDictLN_vectorlETGeoVolumeAssemblycLcLThreadData_tmUcOallocatorlETGeoVolumeAssemblycLcLThreadData_tmUgRsPgR);
   G__get_linked_tagnum_fwd(&G__CycSrimDictLN_reverse_iteratorlEvectorlETGeoVolumeAssemblycLcLThreadData_tmUcOallocatorlETGeoVolumeAssemblycLcLThreadData_tmUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__CycSrimDictLN_maplElongcOTGeoNavigatorArraymUcOlesslElonggRcOallocatorlEpairlEconstsPlongcOTGeoNavigatorArraymUgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__CycSrimDictLN_TGraph);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__CycSrimDictLN_CycSrim),sizeof(CycSrim),-1,295168,"SRIM",G__setup_memvarCycSrim,G__setup_memfuncCycSrim);
   G__get_linked_tagnum_fwd(&G__CycSrimDictLN_CycSrimcLcLsrimDensityUnits);
   G__get_linked_tagnum_fwd(&G__CycSrimDictLN_CycSrimcLcLEMaterials);
}
extern "C" void G__cpp_setupCycSrimDict(void) {
  G__check_setup_version(30051515,"G__cpp_setupCycSrimDict()");
  G__set_cpp_environmentCycSrimDict();
  G__cpp_setup_tagtableCycSrimDict();

  G__cpp_setup_inheritanceCycSrimDict();

  G__cpp_setup_typetableCycSrimDict();

  G__cpp_setup_memvarCycSrimDict();

  G__cpp_setup_memfuncCycSrimDict();
  G__cpp_setup_globalCycSrimDict();
  G__cpp_setup_funcCycSrimDict();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncCycSrimDict();
  return;
}
class G__cpp_setup_initCycSrimDict {
  public:
    G__cpp_setup_initCycSrimDict() { G__add_setup_func("CycSrimDict",(G__incsetup)(&G__cpp_setupCycSrimDict)); G__call_setup_funcs(); }
   ~G__cpp_setup_initCycSrimDict() { G__remove_setup_func("CycSrimDict"); }
};
G__cpp_setup_initCycSrimDict G__cpp_setup_initializerCycSrimDict;

