//
// File generated by rootcint at Thu Feb  8 11:17:52 2018

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME monaAnaDict
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "monaAnaDict.h"

#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TInterpreter.h"
#include "TVirtualMutex.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"
#include "TFileMergeInfo.h"

// Direct notice to TROOT of the dictionary's loading.
namespace {
   static struct DictInit {
      DictInit() {
         ROOT::RegisterModule();
      }
   } __TheDictionaryInitializer;
}

// START OF SHADOWS

namespace ROOTShadow {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOTShadow
// END OF SHADOWS

namespace ROOTDict {
   void MonaAnalyzedEvent_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void *new_MonaAnalyzedEvent(void *p = 0);
   static void *newArray_MonaAnalyzedEvent(Long_t size, void *p);
   static void delete_MonaAnalyzedEvent(void *p);
   static void deleteArray_MonaAnalyzedEvent(void *p);
   static void destruct_MonaAnalyzedEvent(void *p);
   static void streamer_MonaAnalyzedEvent(TBuffer &buf, void *obj);

   // Function generating the singleton type initializer
   static ROOT::TGenericClassInfo *GenerateInitInstanceLocal(const ::MonaAnalyzedEvent*)
   {
      ::MonaAnalyzedEvent *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::MonaAnalyzedEvent >(0);
      static ::ROOT::TGenericClassInfo 
         instance("MonaAnalyzedEvent", ::MonaAnalyzedEvent::Class_Version(), "/projects/mona-sim/baumann/st_mona/src/../include/mona_analysis.hh", 22,
                  typeid(::MonaAnalyzedEvent), ::ROOT::DefineBehavior(ptr, ptr),
                  &::MonaAnalyzedEvent::Dictionary, isa_proxy, 0,
                  sizeof(::MonaAnalyzedEvent) );
      instance.SetNew(&new_MonaAnalyzedEvent);
      instance.SetNewArray(&newArray_MonaAnalyzedEvent);
      instance.SetDelete(&delete_MonaAnalyzedEvent);
      instance.SetDeleteArray(&deleteArray_MonaAnalyzedEvent);
      instance.SetDestructor(&destruct_MonaAnalyzedEvent);
      instance.SetStreamerFunc(&streamer_MonaAnalyzedEvent);
      return &instance;
   }
   ROOT::TGenericClassInfo *GenerateInitInstance(const ::MonaAnalyzedEvent*)
   {
      return GenerateInitInstanceLocal((::MonaAnalyzedEvent*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::MonaAnalyzedEvent*)0x0); R__UseDummy(_R__UNIQUE_(Init));
} // end of namespace ROOTDict

//______________________________________________________________________________
atomic_TClass_ptr MonaAnalyzedEvent::fgIsA(0);  // static to hold class pointer

//______________________________________________________________________________
const char *MonaAnalyzedEvent::Class_Name()
{
   return "MonaAnalyzedEvent";
}

//______________________________________________________________________________
const char *MonaAnalyzedEvent::ImplFileName()
{
   return ::ROOTDict::GenerateInitInstanceLocal((const ::MonaAnalyzedEvent*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int MonaAnalyzedEvent::ImplFileLine()
{
   return ::ROOTDict::GenerateInitInstanceLocal((const ::MonaAnalyzedEvent*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void MonaAnalyzedEvent::Dictionary()
{
   fgIsA = ::ROOTDict::GenerateInitInstanceLocal((const ::MonaAnalyzedEvent*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *MonaAnalyzedEvent::Class()
{
   if (!fgIsA) { R__LOCKGUARD2(gCINTMutex); if(!fgIsA) {fgIsA = ::ROOTDict::GenerateInitInstanceLocal((const ::MonaAnalyzedEvent*)0x0)->GetClass();} }
   return fgIsA;
}

//______________________________________________________________________________
void MonaAnalyzedEvent::Streamer(TBuffer &R__b)
{
   // Stream an object of class MonaAnalyzedEvent.

   UInt_t R__s, R__c;
   if (R__b.IsReading()) {
      Version_t R__v = R__b.ReadVersion(&R__s, &R__c); if (R__v) { }
      TObject::Streamer(R__b);
      R__b >> manDE;
      R__b >> manDESwitch;
      vTPos.Streamer(R__b);
      vNPos.Streamer(R__b);
      vN2Pos.Streamer(R__b);
      vN3Pos.Streamer(R__b);
      vN4Pos.Streamer(R__b);
      vG1NPos.Streamer(R__b);
      vG2NPos.Streamer(R__b);
      vG3NPos.Streamer(R__b);
      vG4NPos.Streamer(R__b);
      vG5NPos.Streamer(R__b);
      vG6NPos.Streamer(R__b);
      lvN.Streamer(R__b);
      lvN2.Streamer(R__b);
      lvN3.Streamer(R__b);
      lvN4.Streamer(R__b);
      lvG1N.Streamer(R__b);
      lvG2N.Streamer(R__b);
      lvG3N.Streamer(R__b);
      lvG4N.Streamer(R__b);
      lvG5N.Streamer(R__b);
      lvG6N.Streamer(R__b);
      lvFCosy.Streamer(R__b);
      lvFSchill.Streamer(R__b);
      lvFFit.Streamer(R__b);
      R__b.ReadStaticArray((double*)deltaE);
      R__b >> EDecay1;
      R__b >> EDecay2;
      R__b >> EDecayTotal;
      R__b >> EDecayTotalG1and2;
      R__b >> EDecayG1;
      R__b >> EDecayG2;
      R__b >> EDecayG3;
      R__b >> EDecayG4;
      R__b >> EDecayG5;
      R__b >> EDecayG6;
      R__b >> EDecayGHigh;
      R__b >> EDecayGLow;
      R__b >> EDecayG_2neutron;
      R__b >> EDecayTotalG3and4;
      R__b >> EDecayG_3neutron;
      R__b >> EDecayTotalG12and3;
      R__b >> EDecay4body;
      R__b >> EDecay5body;
      R__b >> EDecay5body_True;
      R__b.ReadStaticArray((double*)altExenCosy);
      R__b.ReadStaticArray((double*)altExenSchill);
      R__b.ReadStaticArray((double*)altExenFit);
      R__b >> tLab;
      R__b >> tLab2;
      R__b >> vRel;
      R__b >> vRel2;
      R__b >> nVel;
      R__b >> nVel2;
      R__b >> fVel;
      R__b >> fragKinE;
      R__b >> neutronKinE;
      R__b >> nTheta;
      R__b >> nPhi;
      R__b >> neutronKinE2;
      R__b >> nTheta2;
      R__b >> nPhi2;
      R__b >> fTheta;
      R__b >> fPhi;
      R__b >> fAngleX;
      R__b >> fAngleY;
      R__b >> nAngleX;
      R__b >> nAngleY;
      R__b >> nAngleX2;
      R__b >> nAngleY2;
      R__b >> fpATA;
      R__b >> fpBTA;
      R__b >> fpYTA;
      R__b >> delta;
      R__b >> fYfp;
      R__b >> fBfp;
      R__b >> fXfp;
      R__b >> fAfp;
      R__b >> Tsys_CosTheta1;
      R__b >> Tsys_CosTheta2;
      R__b >> Ysys_CosTheta1;
      R__b >> Ysys_CosTheta2;
      R__b >> Tsys_Ex_Et1;
      R__b >> Tsys_Ex_Et2;
      R__b >> Ysys_Ex_Et1;
      R__b >> Ysys_Ex_Et2;
      R__b >> Tsys_CosTheta1_noRes;
      R__b >> Tsys_CosTheta2_noRes;
      R__b >> Ysys_CosTheta1_noRes;
      R__b >> Ysys_CosTheta2_noRes;
      R__b >> Tsys_Ex_Et1_noRes;
      R__b >> Tsys_Ex_Et2_noRes;
      R__b >> Ysys_Ex_Et1_noRes;
      R__b >> Ysys_Ex_Et2_noRes;
      R__b >> Pz_FragN;
      R__b >> Pz_Frag;
      R__b >> Ppar_Frag;
      R__b >> Pperp_Frag;
      R__b >> Ptot_Frag;
      R__b >> nnCM_ppar1;
      R__b >> nnCM_ppar2;
      R__b >> nnCM_pperp1;
      R__b >> nnCM_pperp2;
      R__b >> Theta_3body;
      R__b >> Phi_3body;
      R__b >> n1n2costhetaCM;
      R__b >> tflatfoil;
      R__b >> bulge;
      R__b >> test;
      R__b >> srimTarget;
      R__b >> srimFoil;
      R__b.CheckByteCount(R__s, R__c, MonaAnalyzedEvent::IsA());
   } else {
      R__c = R__b.WriteVersion(MonaAnalyzedEvent::IsA(), kTRUE);
      TObject::Streamer(R__b);
      R__b << manDE;
      R__b << manDESwitch;
      vTPos.Streamer(R__b);
      vNPos.Streamer(R__b);
      vN2Pos.Streamer(R__b);
      vN3Pos.Streamer(R__b);
      vN4Pos.Streamer(R__b);
      vG1NPos.Streamer(R__b);
      vG2NPos.Streamer(R__b);
      vG3NPos.Streamer(R__b);
      vG4NPos.Streamer(R__b);
      vG5NPos.Streamer(R__b);
      vG6NPos.Streamer(R__b);
      lvN.Streamer(R__b);
      lvN2.Streamer(R__b);
      lvN3.Streamer(R__b);
      lvN4.Streamer(R__b);
      lvG1N.Streamer(R__b);
      lvG2N.Streamer(R__b);
      lvG3N.Streamer(R__b);
      lvG4N.Streamer(R__b);
      lvG5N.Streamer(R__b);
      lvG6N.Streamer(R__b);
      lvFCosy.Streamer(R__b);
      lvFSchill.Streamer(R__b);
      lvFFit.Streamer(R__b);
      R__b.WriteArray(deltaE, 3);
      R__b << EDecay1;
      R__b << EDecay2;
      R__b << EDecayTotal;
      R__b << EDecayTotalG1and2;
      R__b << EDecayG1;
      R__b << EDecayG2;
      R__b << EDecayG3;
      R__b << EDecayG4;
      R__b << EDecayG5;
      R__b << EDecayG6;
      R__b << EDecayGHigh;
      R__b << EDecayGLow;
      R__b << EDecayG_2neutron;
      R__b << EDecayTotalG3and4;
      R__b << EDecayG_3neutron;
      R__b << EDecayTotalG12and3;
      R__b << EDecay4body;
      R__b << EDecay5body;
      R__b << EDecay5body_True;
      R__b.WriteArray(altExenCosy, 3);
      R__b.WriteArray(altExenSchill, 3);
      R__b.WriteArray(altExenFit, 3);
      R__b << tLab;
      R__b << tLab2;
      R__b << vRel;
      R__b << vRel2;
      R__b << nVel;
      R__b << nVel2;
      R__b << fVel;
      R__b << fragKinE;
      R__b << neutronKinE;
      R__b << nTheta;
      R__b << nPhi;
      R__b << neutronKinE2;
      R__b << nTheta2;
      R__b << nPhi2;
      R__b << fTheta;
      R__b << fPhi;
      R__b << fAngleX;
      R__b << fAngleY;
      R__b << nAngleX;
      R__b << nAngleY;
      R__b << nAngleX2;
      R__b << nAngleY2;
      R__b << fpATA;
      R__b << fpBTA;
      R__b << fpYTA;
      R__b << delta;
      R__b << fYfp;
      R__b << fBfp;
      R__b << fXfp;
      R__b << fAfp;
      R__b << Tsys_CosTheta1;
      R__b << Tsys_CosTheta2;
      R__b << Ysys_CosTheta1;
      R__b << Ysys_CosTheta2;
      R__b << Tsys_Ex_Et1;
      R__b << Tsys_Ex_Et2;
      R__b << Ysys_Ex_Et1;
      R__b << Ysys_Ex_Et2;
      R__b << Tsys_CosTheta1_noRes;
      R__b << Tsys_CosTheta2_noRes;
      R__b << Ysys_CosTheta1_noRes;
      R__b << Ysys_CosTheta2_noRes;
      R__b << Tsys_Ex_Et1_noRes;
      R__b << Tsys_Ex_Et2_noRes;
      R__b << Ysys_Ex_Et1_noRes;
      R__b << Ysys_Ex_Et2_noRes;
      R__b << Pz_FragN;
      R__b << Pz_Frag;
      R__b << Ppar_Frag;
      R__b << Pperp_Frag;
      R__b << Ptot_Frag;
      R__b << nnCM_ppar1;
      R__b << nnCM_ppar2;
      R__b << nnCM_pperp1;
      R__b << nnCM_pperp2;
      R__b << Theta_3body;
      R__b << Phi_3body;
      R__b << n1n2costhetaCM;
      R__b << tflatfoil;
      R__b << bulge;
      R__b << test;
      R__b << srimTarget;
      R__b << srimFoil;
      R__b.SetByteCount(R__c, kTRUE);
   }
}

//______________________________________________________________________________
void MonaAnalyzedEvent::ShowMembers(TMemberInspector &R__insp)
{
      // Inspect the data members of an object of class MonaAnalyzedEvent.
      TClass *R__cl = ::MonaAnalyzedEvent::IsA();
      if (R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__insp.GetParent(), "manDE", &manDE);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "manDESwitch", &manDESwitch);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "vTPos", &vTPos);
      R__insp.InspectMember(vTPos, "vTPos.");
      R__insp.Inspect(R__cl, R__insp.GetParent(), "vNPos", &vNPos);
      R__insp.InspectMember(vNPos, "vNPos.");
      R__insp.Inspect(R__cl, R__insp.GetParent(), "vN2Pos", &vN2Pos);
      R__insp.InspectMember(vN2Pos, "vN2Pos.");
      R__insp.Inspect(R__cl, R__insp.GetParent(), "vN3Pos", &vN3Pos);
      R__insp.InspectMember(vN3Pos, "vN3Pos.");
      R__insp.Inspect(R__cl, R__insp.GetParent(), "vN4Pos", &vN4Pos);
      R__insp.InspectMember(vN4Pos, "vN4Pos.");
      R__insp.Inspect(R__cl, R__insp.GetParent(), "vG1NPos", &vG1NPos);
      R__insp.InspectMember(vG1NPos, "vG1NPos.");
      R__insp.Inspect(R__cl, R__insp.GetParent(), "vG2NPos", &vG2NPos);
      R__insp.InspectMember(vG2NPos, "vG2NPos.");
      R__insp.Inspect(R__cl, R__insp.GetParent(), "vG3NPos", &vG3NPos);
      R__insp.InspectMember(vG3NPos, "vG3NPos.");
      R__insp.Inspect(R__cl, R__insp.GetParent(), "vG4NPos", &vG4NPos);
      R__insp.InspectMember(vG4NPos, "vG4NPos.");
      R__insp.Inspect(R__cl, R__insp.GetParent(), "vG5NPos", &vG5NPos);
      R__insp.InspectMember(vG5NPos, "vG5NPos.");
      R__insp.Inspect(R__cl, R__insp.GetParent(), "vG6NPos", &vG6NPos);
      R__insp.InspectMember(vG6NPos, "vG6NPos.");
      R__insp.Inspect(R__cl, R__insp.GetParent(), "lvN", &lvN);
      R__insp.InspectMember(lvN, "lvN.");
      R__insp.Inspect(R__cl, R__insp.GetParent(), "lvN2", &lvN2);
      R__insp.InspectMember(lvN2, "lvN2.");
      R__insp.Inspect(R__cl, R__insp.GetParent(), "lvN3", &lvN3);
      R__insp.InspectMember(lvN3, "lvN3.");
      R__insp.Inspect(R__cl, R__insp.GetParent(), "lvN4", &lvN4);
      R__insp.InspectMember(lvN4, "lvN4.");
      R__insp.Inspect(R__cl, R__insp.GetParent(), "lvG1N", &lvG1N);
      R__insp.InspectMember(lvG1N, "lvG1N.");
      R__insp.Inspect(R__cl, R__insp.GetParent(), "lvG2N", &lvG2N);
      R__insp.InspectMember(lvG2N, "lvG2N.");
      R__insp.Inspect(R__cl, R__insp.GetParent(), "lvG3N", &lvG3N);
      R__insp.InspectMember(lvG3N, "lvG3N.");
      R__insp.Inspect(R__cl, R__insp.GetParent(), "lvG4N", &lvG4N);
      R__insp.InspectMember(lvG4N, "lvG4N.");
      R__insp.Inspect(R__cl, R__insp.GetParent(), "lvG5N", &lvG5N);
      R__insp.InspectMember(lvG5N, "lvG5N.");
      R__insp.Inspect(R__cl, R__insp.GetParent(), "lvG6N", &lvG6N);
      R__insp.InspectMember(lvG6N, "lvG6N.");
      R__insp.Inspect(R__cl, R__insp.GetParent(), "lvFCosy", &lvFCosy);
      R__insp.InspectMember(lvFCosy, "lvFCosy.");
      R__insp.Inspect(R__cl, R__insp.GetParent(), "lvFSchill", &lvFSchill);
      R__insp.InspectMember(lvFSchill, "lvFSchill.");
      R__insp.Inspect(R__cl, R__insp.GetParent(), "lvFFit", &lvFFit);
      R__insp.InspectMember(lvFFit, "lvFFit.");
      R__insp.Inspect(R__cl, R__insp.GetParent(), "deltaE[3]", deltaE);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "EDecay1", &EDecay1);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "EDecay2", &EDecay2);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "EDecayTotal", &EDecayTotal);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "EDecayTotalG1and2", &EDecayTotalG1and2);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "EDecayG1", &EDecayG1);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "EDecayG2", &EDecayG2);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "EDecayG3", &EDecayG3);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "EDecayG4", &EDecayG4);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "EDecayG5", &EDecayG5);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "EDecayG6", &EDecayG6);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "EDecayGHigh", &EDecayGHigh);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "EDecayGLow", &EDecayGLow);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "EDecayG_2neutron", &EDecayG_2neutron);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "EDecayTotalG3and4", &EDecayTotalG3and4);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "EDecayG_3neutron", &EDecayG_3neutron);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "EDecayTotalG12and3", &EDecayTotalG12and3);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "EDecay4body", &EDecay4body);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "EDecay5body", &EDecay5body);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "EDecay5body_True", &EDecay5body_True);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "altExenCosy[3]", altExenCosy);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "altExenSchill[3]", altExenSchill);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "altExenFit[3]", altExenFit);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "tLab", &tLab);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "tLab2", &tLab2);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "vRel", &vRel);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "vRel2", &vRel2);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "nVel", &nVel);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "nVel2", &nVel2);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fVel", &fVel);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fragKinE", &fragKinE);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "neutronKinE", &neutronKinE);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "nTheta", &nTheta);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "nPhi", &nPhi);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "neutronKinE2", &neutronKinE2);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "nTheta2", &nTheta2);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "nPhi2", &nPhi2);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fTheta", &fTheta);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fPhi", &fPhi);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fAngleX", &fAngleX);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fAngleY", &fAngleY);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "nAngleX", &nAngleX);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "nAngleY", &nAngleY);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "nAngleX2", &nAngleX2);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "nAngleY2", &nAngleY2);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fpATA", &fpATA);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fpBTA", &fpBTA);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fpYTA", &fpYTA);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "delta", &delta);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fYfp", &fYfp);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fBfp", &fBfp);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fXfp", &fXfp);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fAfp", &fAfp);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "Tsys_CosTheta1", &Tsys_CosTheta1);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "Tsys_CosTheta2", &Tsys_CosTheta2);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "Ysys_CosTheta1", &Ysys_CosTheta1);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "Ysys_CosTheta2", &Ysys_CosTheta2);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "Tsys_Ex_Et1", &Tsys_Ex_Et1);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "Tsys_Ex_Et2", &Tsys_Ex_Et2);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "Ysys_Ex_Et1", &Ysys_Ex_Et1);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "Ysys_Ex_Et2", &Ysys_Ex_Et2);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "Tsys_CosTheta1_noRes", &Tsys_CosTheta1_noRes);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "Tsys_CosTheta2_noRes", &Tsys_CosTheta2_noRes);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "Ysys_CosTheta1_noRes", &Ysys_CosTheta1_noRes);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "Ysys_CosTheta2_noRes", &Ysys_CosTheta2_noRes);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "Tsys_Ex_Et1_noRes", &Tsys_Ex_Et1_noRes);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "Tsys_Ex_Et2_noRes", &Tsys_Ex_Et2_noRes);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "Ysys_Ex_Et1_noRes", &Ysys_Ex_Et1_noRes);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "Ysys_Ex_Et2_noRes", &Ysys_Ex_Et2_noRes);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "Pz_FragN", &Pz_FragN);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "Pz_Frag", &Pz_Frag);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "Ppar_Frag", &Ppar_Frag);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "Pperp_Frag", &Pperp_Frag);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "Ptot_Frag", &Ptot_Frag);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "nnCM_ppar1", &nnCM_ppar1);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "nnCM_ppar2", &nnCM_ppar2);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "nnCM_pperp1", &nnCM_pperp1);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "nnCM_pperp2", &nnCM_pperp2);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "Theta_3body", &Theta_3body);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "Phi_3body", &Phi_3body);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "n1n2costhetaCM", &n1n2costhetaCM);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fMap", (void*)&fMap);
      R__insp.InspectMember("CosyMap", (void*)&fMap, "fMap.", true);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fInvMap", (void*)&fInvMap);
      R__insp.InspectMember("CosyMap", (void*)&fInvMap, "fInvMap.", true);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fragA", &fragA);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fragQ", &fragQ);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "dTarg", &dTarg);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "tflatfoil", &tflatfoil);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "bulge", &bulge);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "test", &test);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "targA", &targA);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "targZ", &targZ);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "monaDist", &monaDist);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fragMassExcess", &fragMassExcess);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fRageny", (void*)&fRageny);
      R__insp.InspectMember("StRageny", (void*)&fRageny, "fRageny.", true);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*matTarget", &matTarget);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*srimTarget", &srimTarget);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*srimFoil", &srimFoil);
      TObject::ShowMembers(R__insp);
}

namespace ROOTDict {
   // Wrappers around operator new
   static void *new_MonaAnalyzedEvent(void *p) {
      return  p ? new(p) ::MonaAnalyzedEvent : new ::MonaAnalyzedEvent;
   }
   static void *newArray_MonaAnalyzedEvent(Long_t nElements, void *p) {
      return p ? new(p) ::MonaAnalyzedEvent[nElements] : new ::MonaAnalyzedEvent[nElements];
   }
   // Wrapper around operator delete
   static void delete_MonaAnalyzedEvent(void *p) {
      delete ((::MonaAnalyzedEvent*)p);
   }
   static void deleteArray_MonaAnalyzedEvent(void *p) {
      delete [] ((::MonaAnalyzedEvent*)p);
   }
   static void destruct_MonaAnalyzedEvent(void *p) {
      typedef ::MonaAnalyzedEvent current_t;
      ((current_t*)p)->~current_t();
   }
   // Wrapper around a custom streamer member function.
   static void streamer_MonaAnalyzedEvent(TBuffer &buf, void *obj) {
      ((::MonaAnalyzedEvent*)obj)->::MonaAnalyzedEvent::Streamer(buf);
   }
} // end of namespace ROOTDict for class ::MonaAnalyzedEvent

/********************************************************
* monaAnaDict.cxx
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtablemonaAnaDict();

extern "C" void G__set_cpp_environmentmonaAnaDict() {
  G__cpp_reset_tagtablemonaAnaDict();
}
#include <new>
extern "C" int G__cpp_dllrevmonaAnaDict() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* MonaAnalyzedEvent */
static int G__monaAnaDict_815_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((MonaAnalyzedEvent*) G__getstructoffset())->initTarget();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__monaAnaDict_815_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   MonaAnalyzedEvent* p = NULL;
   char* gvp = (char*) G__getgvp();
   int n = G__getaryconstruct();
   if (n) {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new MonaAnalyzedEvent[n];
     } else {
       p = new((void*) gvp) MonaAnalyzedEvent[n];
     }
   } else {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new MonaAnalyzedEvent;
     } else {
       p = new((void*) gvp) MonaAnalyzedEvent;
     }
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__monaAnaDictLN_MonaAnalyzedEvent));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__monaAnaDict_815_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((MonaAnalyzedEvent*) G__getstructoffset())->reset();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__monaAnaDict_815_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((MonaAnalyzedEvent*) G__getstructoffset())->ana((CalMonaEvent*) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__monaAnaDict_815_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((MonaAnalyzedEvent*) G__getstructoffset())->applyInvMap((ParticleCoordinates*) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__monaAnaDict_815_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((MonaAnalyzedEvent*) G__getstructoffset())->JacobiCorr(
*((TLorentzVector*) G__int(libp->para[0])), *((TLorentzVector*) G__int(libp->para[1]))
, *((TLorentzVector*) G__int(libp->para[2])), (Double_t) G__double(libp->para[3])
, (Double_t) G__double(libp->para[4]), (Double_t) G__double(libp->para[5])
, (double*) G__int(libp->para[6]), (double*) G__int(libp->para[7])
, *(double*) G__Doubleref(&libp->para[8]), *(double*) G__Doubleref(&libp->para[9])
, *(double*) G__Doubleref(&libp->para[10]), *(double*) G__Doubleref(&libp->para[11])
, *(double*) G__Doubleref(&libp->para[12]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__monaAnaDict_815_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((MonaAnalyzedEvent*) G__getstructoffset())->setMaps(*((CosyMap*) G__int(libp->para[0])), *((CosyMap*) G__int(libp->para[1])));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__monaAnaDict_815_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((MonaAnalyzedEvent*) G__getstructoffset())->setCycSrim((CycSrim*) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__monaAnaDict_815_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((MonaAnalyzedEvent*) G__getstructoffset())->setSrimFoil((CycSrim*) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__monaAnaDict_815_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) MonaAnalyzedEvent::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__monaAnaDict_815_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) MonaAnalyzedEvent::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__monaAnaDict_815_0_12(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) MonaAnalyzedEvent::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__monaAnaDict_815_0_13(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      MonaAnalyzedEvent::Dictionary();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__monaAnaDict_815_0_17(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((MonaAnalyzedEvent*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__monaAnaDict_815_0_18(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) MonaAnalyzedEvent::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__monaAnaDict_815_0_19(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) MonaAnalyzedEvent::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__monaAnaDict_815_0_20(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) MonaAnalyzedEvent::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__monaAnaDict_815_0_21(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) MonaAnalyzedEvent::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__monaAnaDict_815_0_22(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   MonaAnalyzedEvent* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new MonaAnalyzedEvent(*(MonaAnalyzedEvent*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__monaAnaDictLN_MonaAnalyzedEvent));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef MonaAnalyzedEvent G__TMonaAnalyzedEvent;
static int G__monaAnaDict_815_0_23(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 1
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (MonaAnalyzedEvent*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((MonaAnalyzedEvent*) (soff+(sizeof(MonaAnalyzedEvent)*i)))->~G__TMonaAnalyzedEvent();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (MonaAnalyzedEvent*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((MonaAnalyzedEvent*) (soff))->~G__TMonaAnalyzedEvent();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G__monaAnaDict_815_0_24(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   MonaAnalyzedEvent* dest = (MonaAnalyzedEvent*) G__getstructoffset();
   *dest = *(MonaAnalyzedEvent*) libp->para[0].ref;
   const MonaAnalyzedEvent& obj = *dest;
   result7->ref = (long) (&obj);
   result7->obj.i = (long) (&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* MonaAnalyzedEvent */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncmonaAnaDict {
 public:
  G__Sizep2memfuncmonaAnaDict(): p(&G__Sizep2memfuncmonaAnaDict::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncmonaAnaDict::*p)();
};

size_t G__get_sizep2memfuncmonaAnaDict()
{
  G__Sizep2memfuncmonaAnaDict a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritancemonaAnaDict() {

   /* Setting up class inheritance */
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__monaAnaDictLN_MonaAnalyzedEvent))) {
     MonaAnalyzedEvent *G__Lderived;
     G__Lderived=(MonaAnalyzedEvent*)0x1000;
     {
       TObject *G__Lpbase=(TObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__monaAnaDictLN_MonaAnalyzedEvent),G__get_linked_tagnum(&G__monaAnaDictLN_TObject),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
   }
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetablemonaAnaDict() {

   /* Setting up typedef entry */
   G__search_typename2("Double_t",100,-1,0,-1);
   G__setnewtype(-1,"Double 8 bytes",0);
   G__search_typename2("Version_t",115,-1,0,-1);
   G__setnewtype(-1,"Class version identifier (short)",0);
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__monaAnaDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__monaAnaDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__monaAnaDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__monaAnaDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__monaAnaDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__monaAnaDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__monaAnaDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__monaAnaDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__monaAnaDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__monaAnaDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<std::bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__monaAnaDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__monaAnaDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*>",117,G__get_linked_tagnum(&G__monaAnaDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long>",117,G__get_linked_tagnum(&G__monaAnaDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long,const TObject**>",117,G__get_linked_tagnum(&G__monaAnaDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<std::string,TObjArray*>",117,G__get_linked_tagnum(&G__monaAnaDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TObjArray*>",117,G__get_linked_tagnum(&G__monaAnaDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TObjArray*>",117,G__get_linked_tagnum(&G__monaAnaDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TObjArray*,less<string> >",117,G__get_linked_tagnum(&G__monaAnaDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTBase<Float_t>",117,G__get_linked_tagnum(&G__monaAnaDictLN_TMatrixTBaselEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTBase<Double_t>",117,G__get_linked_tagnum(&G__monaAnaDictLN_TMatrixTBaselEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Float_t>",117,G__get_linked_tagnum(&G__monaAnaDictLN_TVectorTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Double_t>",117,G__get_linked_tagnum(&G__monaAnaDictLN_TVectorTlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixT<Float_t>",117,G__get_linked_tagnum(&G__monaAnaDictLN_TMatrixTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTRow_const<Float_t>",117,G__get_linked_tagnum(&G__monaAnaDictLN_TMatrixTRow_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTColumn_const<Float_t>",117,G__get_linked_tagnum(&G__monaAnaDictLN_TMatrixTColumn_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTDiag_const<Float_t>",117,G__get_linked_tagnum(&G__monaAnaDictLN_TMatrixTDiag_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTFlat_const<Float_t>",117,G__get_linked_tagnum(&G__monaAnaDictLN_TMatrixTFlat_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSub_const<Float_t>",117,G__get_linked_tagnum(&G__monaAnaDictLN_TMatrixTSub_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseRow_const<Float_t>",117,G__get_linked_tagnum(&G__monaAnaDictLN_TMatrixTSparseRow_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseDiag_const<Float_t>",117,G__get_linked_tagnum(&G__monaAnaDictLN_TMatrixTSparseDiag_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTRow<Float_t>",117,G__get_linked_tagnum(&G__monaAnaDictLN_TMatrixTRowlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTColumn<Float_t>",117,G__get_linked_tagnum(&G__monaAnaDictLN_TMatrixTColumnlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTDiag<Float_t>",117,G__get_linked_tagnum(&G__monaAnaDictLN_TMatrixTDiaglEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTFlat<Float_t>",117,G__get_linked_tagnum(&G__monaAnaDictLN_TMatrixTFlatlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSub<Float_t>",117,G__get_linked_tagnum(&G__monaAnaDictLN_TMatrixTSublEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseRow<Float_t>",117,G__get_linked_tagnum(&G__monaAnaDictLN_TMatrixTSparseRowlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseDiag<Float_t>",117,G__get_linked_tagnum(&G__monaAnaDictLN_TMatrixTSparseDiaglEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TElementActionT<Float_t>",117,G__get_linked_tagnum(&G__monaAnaDictLN_TElementActionTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TElementPosActionT<Float_t>",117,G__get_linked_tagnum(&G__monaAnaDictLN_TElementPosActionTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<CosyMapLine>",117,G__get_linked_tagnum(&G__monaAnaDictLN_vectorlECosyMapLinecOallocatorlECosyMapLinegRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__monaAnaDictLN_reverse_iteratorlEvectorlECosyMapLinecOallocatorlECosyMapLinegRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__monaAnaDictLN_vectorlECosyMapLinecOallocatorlECosyMapLinegRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__monaAnaDictLN_reverse_iteratorlEvectorlECosyMapLinecOallocatorlECosyMapLinegRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__monaAnaDictLN_vectorlECosyMapLinecOallocatorlECosyMapLinegRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<Int_t,TGeoElementRN*>",117,G__get_linked_tagnum(&G__monaAnaDictLN_maplEintcOTGeoElementRNmUcOlesslEintgRcOallocatorlEpairlEconstsPintcOTGeoElementRNmUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<int,TGeoElementRN*>",117,G__get_linked_tagnum(&G__monaAnaDictLN_maplEintcOTGeoElementRNmUcOlesslEintgRcOallocatorlEpairlEconstsPintcOTGeoElementRNmUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<int,TGeoElementRN*,less<int> >",117,G__get_linked_tagnum(&G__monaAnaDictLN_maplEintcOTGeoElementRNmUcOlesslEintgRcOallocatorlEpairlEconstsPintcOTGeoElementRNmUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<ThreadData_t*>",117,G__get_linked_tagnum(&G__monaAnaDictLN_vectorlETGeoVolumeAssemblycLcLThreadData_tmUcOallocatorlETGeoVolumeAssemblycLcLThreadData_tmUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__monaAnaDictLN_reverse_iteratorlEvectorlETGeoVolumeAssemblycLcLThreadData_tmUcOallocatorlETGeoVolumeAssemblycLcLThreadData_tmUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__monaAnaDictLN_vectorlETGeoVolumeAssemblycLcLThreadData_tmUcOallocatorlETGeoVolumeAssemblycLcLThreadData_tmUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__monaAnaDictLN_reverse_iteratorlEvectorlETGeoVolumeAssemblycLcLThreadData_tmUcOallocatorlETGeoVolumeAssemblycLcLThreadData_tmUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__monaAnaDictLN_vectorlETGeoVolumeAssemblycLcLThreadData_tmUcOallocatorlETGeoVolumeAssemblycLcLThreadData_tmUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TGeoVolumeAssembly::ThreadData_t*>",117,G__get_linked_tagnum(&G__monaAnaDictLN_vectorlETGeoVolumeAssemblycLcLThreadData_tmUcOallocatorlETGeoVolumeAssemblycLcLThreadData_tmUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<Long_t,TGeoNavigatorArray*>",117,G__get_linked_tagnum(&G__monaAnaDictLN_maplElongcOTGeoNavigatorArraymUcOlesslElonggRcOallocatorlEpairlEconstsPlongcOTGeoNavigatorArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<long,TGeoNavigatorArray*>",117,G__get_linked_tagnum(&G__monaAnaDictLN_maplElongcOTGeoNavigatorArraymUcOlesslElonggRcOallocatorlEpairlEconstsPlongcOTGeoNavigatorArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<long,TGeoNavigatorArray*,less<long> >",117,G__get_linked_tagnum(&G__monaAnaDictLN_maplElongcOTGeoNavigatorArraymUcOlesslElonggRcOallocatorlEpairlEconstsPlongcOTGeoNavigatorArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<Long_t,Int_t>",117,G__get_linked_tagnum(&G__monaAnaDictLN_maplElongcOintcOlesslElonggRcOallocatorlEpairlEconstsPlongcOintgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<StParticle>",117,G__get_linked_tagnum(&G__monaAnaDictLN_vectorlEStParticlecOallocatorlEStParticlegRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__monaAnaDictLN_reverse_iteratorlEvectorlEStParticlecOallocatorlEStParticlegRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__monaAnaDictLN_vectorlEStParticlecOallocatorlEStParticlegRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__monaAnaDictLN_reverse_iteratorlEvectorlEStParticlecOallocatorlEStParticlegRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__monaAnaDictLN_vectorlEStParticlecOallocatorlEStParticlegRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<string>",117,G__get_linked_tagnum(&G__monaAnaDictLN_vectorlEstringcOallocatorlEstringgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__monaAnaDictLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__monaAnaDictLN_vectorlEstringcOallocatorlEstringgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__monaAnaDictLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__monaAnaDictLN_vectorlEstringcOallocatorlEstringgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<int>",117,G__get_linked_tagnum(&G__monaAnaDictLN_vectorlEintcOallocatorlEintgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__monaAnaDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__monaAnaDictLN_vectorlEintcOallocatorlEintgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__monaAnaDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__monaAnaDictLN_vectorlEintcOallocatorlEintgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<StElement>",117,G__get_linked_tagnum(&G__monaAnaDictLN_vectorlEStElementcOallocatorlEStElementgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__monaAnaDictLN_reverse_iteratorlEvectorlEStElementcOallocatorlEStElementgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__monaAnaDictLN_vectorlEStElementcOallocatorlEStElementgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__monaAnaDictLN_reverse_iteratorlEvectorlEStElementcOallocatorlEStElementgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__monaAnaDictLN_vectorlEStElementcOallocatorlEStElementgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<StReaction*>",117,G__get_linked_tagnum(&G__monaAnaDictLN_vectorlEStReactionmUcOallocatorlEStReactionmUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__monaAnaDictLN_reverse_iteratorlEvectorlEStReactionmUcOallocatorlEStReactionmUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__monaAnaDictLN_vectorlEStReactionmUcOallocatorlEStReactionmUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__monaAnaDictLN_reverse_iteratorlEvectorlEStReactionmUcOallocatorlEStReactionmUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__monaAnaDictLN_vectorlEStReactionmUcOallocatorlEStReactionmUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("set<Data,ltData>",117,G__get_linked_tagnum(&G__monaAnaDictLN_setlEDatacOltDatacOallocatorlEDatagRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("set<Data>",117,G__get_linked_tagnum(&G__monaAnaDictLN_setlEDatacOltDatacOallocatorlEDatagRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<RagenyTargetBeam,StInterp*,ltRagenyTB>",117,G__get_linked_tagnum(&G__monaAnaDictLN_maplERagenyTargetBeamcOStInterpmUcOltRagenyTBcOallocatorlEpairlEconstsPRagenyTargetBeamcOStInterpmUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<RagenyTargetBeam,StInterp*>",117,G__get_linked_tagnum(&G__monaAnaDictLN_maplERagenyTargetBeamcOStInterpmUcOltRagenyTBcOallocatorlEpairlEconstsPRagenyTargetBeamcOStInterpmUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* MonaAnalyzedEvent */
static void G__setup_memvarMonaAnalyzedEvent(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__monaAnaDictLN_MonaAnalyzedEvent));
   { MonaAnalyzedEvent *p; p=(MonaAnalyzedEvent*)0x1000; if (p) { }
   G__memvar_setup((void*)((long)(&p->manDE)-(long)(p)),100,0,0,-1,-1,-1,1,"manDE=",0,"for manual control of the deltaE of Schiller map.");
   G__memvar_setup((void*)((long)(&p->manDESwitch)-(long)(p)),105,0,0,-1,-1,-1,1,"manDESwitch=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__monaAnaDictLN_TVector3),-1,-1,4,"vTPos=",0,"target position");
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__monaAnaDictLN_TVector3),-1,-1,4,"vNPos=",0,"neutron position");
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__monaAnaDictLN_TVector3),-1,-1,4,"vN2Pos=",0,"second neutron position");
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__monaAnaDictLN_TVector3),-1,-1,4,"vN3Pos=",0,"third neutron");
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__monaAnaDictLN_TVector3),-1,-1,4,"vN4Pos=",0,"fourth neutron");
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__monaAnaDictLN_TVector3),-1,-1,4,"vG1NPos=",0,"1st Geant4 neutron position  ");
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__monaAnaDictLN_TVector3),-1,-1,4,"vG2NPos=",0,"2nd Geant4 neutron position");
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__monaAnaDictLN_TVector3),-1,-1,4,"vG3NPos=",0,"3rd Geant4 neutron position");
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__monaAnaDictLN_TVector3),-1,-1,4,"vG4NPos=",0,"4th Geant4 neutron position");
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__monaAnaDictLN_TVector3),-1,-1,4,"vG5NPos=",0,"5th Geant4 neutron position");
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__monaAnaDictLN_TVector3),-1,-1,4,"vG6NPos=",0,"6th Geant4 neutron position");
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__monaAnaDictLN_TLorentzVector),-1,-1,4,"lvN=",0,"4-vector of the neutron");
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__monaAnaDictLN_TLorentzVector),-1,-1,4,"lvN2=",0,"4-vector for the second neutron");
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__monaAnaDictLN_TLorentzVector),-1,-1,4,"lvN3=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__monaAnaDictLN_TLorentzVector),-1,-1,4,"lvN4=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__monaAnaDictLN_TLorentzVector),-1,-1,4,"lvG1N=",0,"4-vector for the 1st Geant4 neutron");
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__monaAnaDictLN_TLorentzVector),-1,-1,4,"lvG2N=",0,"4-vector for the 2nd Geant4 neutron");
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__monaAnaDictLN_TLorentzVector),-1,-1,4,"lvG3N=",0,"4-vector for the 3rd Geant4 neutron");
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__monaAnaDictLN_TLorentzVector),-1,-1,4,"lvG4N=",0,"4-vector for the 4th Geant4 neutron");
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__monaAnaDictLN_TLorentzVector),-1,-1,4,"lvG5N=",0,"4-vector for the 5th Geant4 neutron");
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__monaAnaDictLN_TLorentzVector),-1,-1,4,"lvG6N=",0,"4-vector for the 6th Geant4 neutron");
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__monaAnaDictLN_TLorentzVector),-1,-1,4,"lvFCosy=",0,"4-vector of fragment after target, i.e. w/o energy-loss correction (using cosy map)");
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__monaAnaDictLN_TLorentzVector),-1,-1,4,"lvFSchill=",0,"4-vector of fragment after target, i.e. w/o energy-loss correction (using Schiller map)");
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__monaAnaDictLN_TLorentzVector),-1,-1,4,"lvFFit=",0,"4-vector of fragment after target, i.e. w/o energy-loss correction (using Chi^2 min)");
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,4,"deltaE[3]=",0,"energy-loss correction [0]/[1]/[2] - using no/nominal/measured beam energy");
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,4,"EDecay1=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,4,"EDecay2=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,4,"EDecayTotal=",0,"Decay Energies for the 1st and 2nd neutron along with total decay energy");
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,4,"EDecayTotalG1and2=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,4,"EDecayG1=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,4,"EDecayG2=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,4,"EDecayG3=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,4,"EDecayG4=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,4,"EDecayG5=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,4,"EDecayG6=",0,"Decay Energy for the first 6 neutrons from Geant4");
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,4,"EDecayGHigh=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,4,"EDecayGLow=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,4,"EDecayG_2neutron=",0,"high and low decay energies from geant");
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,4,"EDecayTotalG3and4=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,4,"EDecayG_3neutron=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,4,"EDecayTotalG12and3=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,4,"EDecay4body=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,4,"EDecay5body=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,4,"EDecay5body_True=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,4,"altExenCosy[3]=",0,"alternative excitation energy using Cosy Map (index as for deltaE[3])");
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,4,"altExenSchill[3]=",0,"alternative excitation energy using Schiller Map (index as for deltaE[3])");
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,4,"altExenFit[3]=",0,"alternative excitation energy using Chi^2 reconstr.  (index as for deltaE[3])");
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,4,"tLab=",0,"theta lab between fragment and neutron");
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,4,"tLab2=",0,"theta lab between fragment and second neutron");
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,4,"vRel=",0,"velocity difference: v_neutr - v_frag");
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,4,"vRel2=",0,"velocity difference: v_neutr2 - v_frag");
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,4,"nVel=",0,"velocity of neutrons!!: nVel = lvN.Beta() * 30 (cm/ns)");
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,4,"nVel2=",0,"velocity of second neutrons!!: nVel = lvN.Beta() * 30 (cm/ns)");
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,4,"fVel=",0,"velocity of fragment");
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,4,"fragKinE=",0,"Frag kinetic energy");
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,4,"neutronKinE=",0,"Neutron kinetic energy");
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,4,"nTheta=",0,"Neutron theta ?");
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,4,"nPhi=",0,"Neutrons Phi");
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,4,"neutronKinE2=",0,"Second Neutron kinetic energy");
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,4,"nTheta2=",0,"Second Neutron theta ");
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,4,"nPhi2=",0,"Second Neutrons Phi  ");
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,4,"fTheta=",0,"Frag theta");
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,4,"fPhi=",0,"Frag Phi ");
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,4,"fAngleX=",0,"Frag x-angle at target");
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,4,"fAngleY=",0,"Frag y-angle at target");
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,4,"nAngleX=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,4,"nAngleY=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,4,"nAngleX2=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,4,"nAngleY2=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,4,"fpATA=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,4,"fpBTA=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,4,"fpYTA=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,4,"delta=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,4,"fYfp=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,4,"fBfp=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,4,"fXfp=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,4,"fAfp=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,4,"Tsys_CosTheta1=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,4,"Tsys_CosTheta2=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,4,"Ysys_CosTheta1=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,4,"Ysys_CosTheta2=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,4,"Tsys_Ex_Et1=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,4,"Tsys_Ex_Et2=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,4,"Ysys_Ex_Et1=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,4,"Ysys_Ex_Et2=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,4,"Tsys_CosTheta1_noRes=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,4,"Tsys_CosTheta2_noRes=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,4,"Ysys_CosTheta1_noRes=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,4,"Ysys_CosTheta2_noRes=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,4,"Tsys_Ex_Et1_noRes=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,4,"Tsys_Ex_Et2_noRes=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,4,"Ysys_Ex_Et1_noRes=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,4,"Ysys_Ex_Et2_noRes=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,4,"Pz_FragN=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,4,"Pz_Frag=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,4,"Ppar_Frag=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,4,"Pperp_Frag=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,4,"Ptot_Frag=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,4,"nnCM_ppar1=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,4,"nnCM_ppar2=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,4,"nnCM_pperp1=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,4,"nnCM_pperp2=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,4,"Theta_3body=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,4,"Phi_3body=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,4,"n1n2costhetaCM=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__monaAnaDictLN_CosyMap),-1,-1,4,"fMap=",0,"! forward map");
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__monaAnaDictLN_CosyMap),-1,-1,4,"fInvMap=",0,"! (Schiller) inverse map");
   G__memvar_setup((void*)((long)(&p->fragA)-(long)(p)),105,0,0,-1,-1,-1,1,"fragA=",0,"!");
   G__memvar_setup((void*)((long)(&p->fragQ)-(long)(p)),105,0,0,-1,-1,-1,1,"fragQ=",0,"!");
   G__memvar_setup((void*)((long)(&p->dTarg)-(long)(p)),100,0,0,-1,-1,-1,1,"dTarg=",0,"!");
   G__memvar_setup((void*)((long)(&p->tflatfoil)-(long)(p)),100,0,0,-1,-1,-1,1,"tflatfoil=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->bulge)-(long)(p)),100,0,0,-1,-1,-1,1,"bulge=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->test)-(long)(p)),100,0,0,-1,-1,-1,1,"test=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->targA)-(long)(p)),105,0,0,-1,-1,-1,1,"targA=",0,"!");
   G__memvar_setup((void*)((long)(&p->targZ)-(long)(p)),105,0,0,-1,-1,-1,1,"targZ=",0,"!");
   G__memvar_setup((void*)((long)(&p->monaDist)-(long)(p)),100,0,0,-1,-1,-1,1,"monaDist=",0,"!");
   G__memvar_setup((void*)((long)(&p->fragMassExcess)-(long)(p)),100,0,0,-1,-1,-1,1,"fragMassExcess=",0,"! MeV");
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__monaAnaDictLN_StRageny),-1,-1,4,"fRageny=",0,"! energy loss correction");
   G__memvar_setup((void*)((long)(&p->matTarget)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__monaAnaDictLN_StMaterial),-1,-1,1,"matTarget=",0,"! material");
   G__memvar_setup((void*)((long)(&p->srimTarget)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__monaAnaDictLN_CycSrim),-1,-1,1,"srimTarget=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->srimFoil)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__monaAnaDictLN_CycSrim),-1,-1,1,"srimFoil=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__monaAnaDictLN_TClass),G__defined_typename("atomic_TClass_ptr"),-2,4,"fgIsA=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarmonaAnaDict() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncMonaAnalyzedEvent(void) {
   /* MonaAnalyzedEvent */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__monaAnaDictLN_MonaAnalyzedEvent));
   G__memfunc_setup("initTarget",1051,G__monaAnaDict_815_0_1, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("MonaAnalyzedEvent",1733,G__monaAnaDict_815_0_2, 105, G__get_linked_tagnum(&G__monaAnaDictLN_MonaAnalyzedEvent), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("reset",547,G__monaAnaDict_815_0_3, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("ana",304,G__monaAnaDict_815_0_4, 105, -1, -1, 0, 1, 1, 1, 0, "U 'CalMonaEvent' - 0 - e", "/< analyze event", (void*) NULL, 0);
   G__memfunc_setup("applyInvMap",1137,G__monaAnaDict_815_0_5, 105, -1, -1, 0, 1, 1, 1, 0, "U 'ParticleCoordinates' - 0 - c", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("JacobiCorr",990,G__monaAnaDict_815_0_6, 121, -1, -1, 0, 13, 1, 1, 0, 
"u 'TLorentzVector' - 0 - lv_F u 'TLorentzVector' - 0 - lv_N1 "
"u 'TLorentzVector' - 0 - lv_N2 d - 'Double_t' 0 - massF "
"d - 'Double_t' 0 - massN1 d - 'Double_t' 0 - massN2 "
"D - - 0 - Tsystem D - - 0 - Ysystem "
"d - - 1 - cosn1n2theta d - - 1 - nCM_ppar1 "
"d - - 1 - nCM_ppar2 d - - 1 - nCM_pperp1 "
"d - - 1 - nCM_pperp2", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("setMaps",733,G__monaAnaDict_815_0_7, 121, -1, -1, 0, 2, 1, 1, 0, 
"u 'CosyMap' - 0 - a u 'CosyMap' - 0 - b", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("setCycSrim",1030,G__monaAnaDict_815_0_8, 121, -1, -1, 0, 1, 1, 1, 0, "U 'CycSrim' - 0 - fSrimTarget", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("setSrimFoil",1137,G__monaAnaDict_815_0_9, 121, -1, -1, 0, 1, 1, 1, 0, "U 'CycSrim' - 0 - fSrimFoil", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Class",502,G__monaAnaDict_815_0_10, 85, G__get_linked_tagnum(&G__monaAnaDictLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (TClass* (*)())(&MonaAnalyzedEvent::Class) ), 0);
   G__memfunc_setup("Class_Name",982,G__monaAnaDict_815_0_11, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&MonaAnalyzedEvent::Class_Name) ), 0);
   G__memfunc_setup("Class_Version",1339,G__monaAnaDict_815_0_12, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (Version_t (*)())(&MonaAnalyzedEvent::Class_Version) ), 0);
   G__memfunc_setup("Dictionary",1046,G__monaAnaDict_815_0_13, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (void (*)())(&MonaAnalyzedEvent::Dictionary) ), 0);
   G__memfunc_setup("IsA",253,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__monaAnaDictLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ShowMembers",1132,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TMemberInspector' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Streamer",835,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("StreamerNVirtual",1656,G__monaAnaDict_815_0_17, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - ClassDef_StreamerNVirtual_b", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DeclFileName",1145,G__monaAnaDict_815_0_18, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&MonaAnalyzedEvent::DeclFileName) ), 0);
   G__memfunc_setup("ImplFileLine",1178,G__monaAnaDict_815_0_19, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&MonaAnalyzedEvent::ImplFileLine) ), 0);
   G__memfunc_setup("ImplFileName",1171,G__monaAnaDict_815_0_20, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&MonaAnalyzedEvent::ImplFileName) ), 0);
   G__memfunc_setup("DeclFileLine",1152,G__monaAnaDict_815_0_21, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&MonaAnalyzedEvent::DeclFileLine) ), 0);
   // automatic copy constructor
   G__memfunc_setup("MonaAnalyzedEvent", 1733, G__monaAnaDict_815_0_22, (int) ('i'), G__get_linked_tagnum(&G__monaAnaDictLN_MonaAnalyzedEvent), -1, 0, 1, 1, 1, 0, "u 'MonaAnalyzedEvent' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~MonaAnalyzedEvent", 1859, G__monaAnaDict_815_0_23, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 0);
   // automatic assignment operator
   G__memfunc_setup("operator=", 937, G__monaAnaDict_815_0_24, (int) ('u'), G__get_linked_tagnum(&G__monaAnaDictLN_MonaAnalyzedEvent), -1, 1, 1, 1, 1, 0, "u 'MonaAnalyzedEvent' - 11 - -", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncmonaAnaDict() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {
}

static void G__cpp_setup_global2() {
}

static void G__cpp_setup_global3() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalmonaAnaDict() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
  G__cpp_setup_global2();
  G__cpp_setup_global3();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {
}

static void G__cpp_setup_func13() {
}

static void G__cpp_setup_func14() {
}

static void G__cpp_setup_func15() {
}

static void G__cpp_setup_func16() {
}

static void G__cpp_setup_func17() {
}

static void G__cpp_setup_func18() {
}

static void G__cpp_setup_func19() {
}

static void G__cpp_setup_func20() {
}

static void G__cpp_setup_func21() {
}

static void G__cpp_setup_func22() {
}

static void G__cpp_setup_func23() {
}

static void G__cpp_setup_func24() {
}

static void G__cpp_setup_func25() {
}

static void G__cpp_setup_func26() {
}

static void G__cpp_setup_func27() {
}

static void G__cpp_setup_func28() {
}

static void G__cpp_setup_func29() {
}

static void G__cpp_setup_func30() {
}

static void G__cpp_setup_func31() {
}

static void G__cpp_setup_func32() {
}

static void G__cpp_setup_func33() {
}

static void G__cpp_setup_func34() {
}

static void G__cpp_setup_func35() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcmonaAnaDict() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
  G__cpp_setup_func13();
  G__cpp_setup_func14();
  G__cpp_setup_func15();
  G__cpp_setup_func16();
  G__cpp_setup_func17();
  G__cpp_setup_func18();
  G__cpp_setup_func19();
  G__cpp_setup_func20();
  G__cpp_setup_func21();
  G__cpp_setup_func22();
  G__cpp_setup_func23();
  G__cpp_setup_func24();
  G__cpp_setup_func25();
  G__cpp_setup_func26();
  G__cpp_setup_func27();
  G__cpp_setup_func28();
  G__cpp_setup_func29();
  G__cpp_setup_func30();
  G__cpp_setup_func31();
  G__cpp_setup_func32();
  G__cpp_setup_func33();
  G__cpp_setup_func34();
  G__cpp_setup_func35();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__monaAnaDictLN_TClass = { "TClass" , 99 , -1 };
G__linked_taginfo G__monaAnaDictLN_TBuffer = { "TBuffer" , 99 , -1 };
G__linked_taginfo G__monaAnaDictLN_TMemberInspector = { "TMemberInspector" , 99 , -1 };
G__linked_taginfo G__monaAnaDictLN_TObject = { "TObject" , 99 , -1 };
G__linked_taginfo G__monaAnaDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__monaAnaDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__monaAnaDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G__monaAnaDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__monaAnaDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR = { "iterator<bidirectional_iterator_tag,TObject*,long,const TObject**,const TObject*&>" , 115 , -1 };
G__linked_taginfo G__monaAnaDictLN_maplElongcOintcOlesslElonggRcOallocatorlEpairlEconstsPlongcOintgRsPgRsPgR = { "map<long,int,less<long>,allocator<pair<const long,int> > >" , 99 , -1 };
G__linked_taginfo G__monaAnaDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR = { "map<string,TObjArray*,less<string>,allocator<pair<const string,TObjArray*> > >" , 99 , -1 };
G__linked_taginfo G__monaAnaDictLN_TMatrixTBaselEfloatgR = { "TMatrixTBase<float>" , 99 , -1 };
G__linked_taginfo G__monaAnaDictLN_TMatrixTBaselEdoublegR = { "TMatrixTBase<double>" , 99 , -1 };
G__linked_taginfo G__monaAnaDictLN_TVectorTlEfloatgR = { "TVectorT<float>" , 99 , -1 };
G__linked_taginfo G__monaAnaDictLN_TVectorTlEdoublegR = { "TVectorT<double>" , 99 , -1 };
G__linked_taginfo G__monaAnaDictLN_TElementActionTlEfloatgR = { "TElementActionT<float>" , 99 , -1 };
G__linked_taginfo G__monaAnaDictLN_TElementPosActionTlEfloatgR = { "TElementPosActionT<float>" , 99 , -1 };
G__linked_taginfo G__monaAnaDictLN_TMatrixTlEfloatgR = { "TMatrixT<float>" , 99 , -1 };
G__linked_taginfo G__monaAnaDictLN_TMatrixTRow_constlEfloatgR = { "TMatrixTRow_const<float>" , 99 , -1 };
G__linked_taginfo G__monaAnaDictLN_TMatrixTRowlEfloatgR = { "TMatrixTRow<float>" , 99 , -1 };
G__linked_taginfo G__monaAnaDictLN_TMatrixTDiag_constlEfloatgR = { "TMatrixTDiag_const<float>" , 99 , -1 };
G__linked_taginfo G__monaAnaDictLN_TMatrixTColumn_constlEfloatgR = { "TMatrixTColumn_const<float>" , 99 , -1 };
G__linked_taginfo G__monaAnaDictLN_TMatrixTFlat_constlEfloatgR = { "TMatrixTFlat_const<float>" , 99 , -1 };
G__linked_taginfo G__monaAnaDictLN_TMatrixTSub_constlEfloatgR = { "TMatrixTSub_const<float>" , 99 , -1 };
G__linked_taginfo G__monaAnaDictLN_TMatrixTSparseRow_constlEfloatgR = { "TMatrixTSparseRow_const<float>" , 99 , -1 };
G__linked_taginfo G__monaAnaDictLN_TMatrixTSparseDiag_constlEfloatgR = { "TMatrixTSparseDiag_const<float>" , 99 , -1 };
G__linked_taginfo G__monaAnaDictLN_TMatrixTColumnlEfloatgR = { "TMatrixTColumn<float>" , 99 , -1 };
G__linked_taginfo G__monaAnaDictLN_TMatrixTDiaglEfloatgR = { "TMatrixTDiag<float>" , 99 , -1 };
G__linked_taginfo G__monaAnaDictLN_TMatrixTFlatlEfloatgR = { "TMatrixTFlat<float>" , 99 , -1 };
G__linked_taginfo G__monaAnaDictLN_TMatrixTSublEfloatgR = { "TMatrixTSub<float>" , 99 , -1 };
G__linked_taginfo G__monaAnaDictLN_TMatrixTSparseRowlEfloatgR = { "TMatrixTSparseRow<float>" , 99 , -1 };
G__linked_taginfo G__monaAnaDictLN_TMatrixTSparseDiaglEfloatgR = { "TMatrixTSparseDiag<float>" , 99 , -1 };
G__linked_taginfo G__monaAnaDictLN_TVector3 = { "TVector3" , 99 , -1 };
G__linked_taginfo G__monaAnaDictLN_TLorentzVector = { "TLorentzVector" , 99 , -1 };
G__linked_taginfo G__monaAnaDictLN_CosyMap = { "CosyMap" , 99 , -1 };
G__linked_taginfo G__monaAnaDictLN_vectorlECosyMapLinecOallocatorlECosyMapLinegRsPgR = { "vector<CosyMapLine,allocator<CosyMapLine> >" , 99 , -1 };
G__linked_taginfo G__monaAnaDictLN_reverse_iteratorlEvectorlECosyMapLinecOallocatorlECosyMapLinegRsPgRcLcLiteratorgR = { "reverse_iterator<vector<CosyMapLine,allocator<CosyMapLine> >::iterator>" , 99 , -1 };
G__linked_taginfo G__monaAnaDictLN_maplEintcOTGeoElementRNmUcOlesslEintgRcOallocatorlEpairlEconstsPintcOTGeoElementRNmUgRsPgRsPgR = { "map<int,TGeoElementRN*,less<int>,allocator<pair<const int,TGeoElementRN*> > >" , 99 , -1 };
G__linked_taginfo G__monaAnaDictLN_vectorlETGeoVolumeAssemblycLcLThreadData_tmUcOallocatorlETGeoVolumeAssemblycLcLThreadData_tmUgRsPgR = { "vector<TGeoVolumeAssembly::ThreadData_t*,allocator<TGeoVolumeAssembly::ThreadData_t*> >" , 99 , -1 };
G__linked_taginfo G__monaAnaDictLN_reverse_iteratorlEvectorlETGeoVolumeAssemblycLcLThreadData_tmUcOallocatorlETGeoVolumeAssemblycLcLThreadData_tmUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TGeoVolumeAssembly::ThreadData_t*,allocator<TGeoVolumeAssembly::ThreadData_t*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__monaAnaDictLN_maplElongcOTGeoNavigatorArraymUcOlesslElonggRcOallocatorlEpairlEconstsPlongcOTGeoNavigatorArraymUgRsPgRsPgR = { "map<long,TGeoNavigatorArray*,less<long>,allocator<pair<const long,TGeoNavigatorArray*> > >" , 99 , -1 };
G__linked_taginfo G__monaAnaDictLN_CycSrim = { "CycSrim" , 99 , -1 };
G__linked_taginfo G__monaAnaDictLN_vectorlEStParticlecOallocatorlEStParticlegRsPgR = { "vector<StParticle,allocator<StParticle> >" , 99 , -1 };
G__linked_taginfo G__monaAnaDictLN_reverse_iteratorlEvectorlEStParticlecOallocatorlEStParticlegRsPgRcLcLiteratorgR = { "reverse_iterator<vector<StParticle,allocator<StParticle> >::iterator>" , 99 , -1 };
G__linked_taginfo G__monaAnaDictLN_vectorlEstringcOallocatorlEstringgRsPgR = { "vector<string,allocator<string> >" , 99 , -1 };
G__linked_taginfo G__monaAnaDictLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<string,allocator<string> >::iterator>" , 99 , -1 };
G__linked_taginfo G__monaAnaDictLN_vectorlEintcOallocatorlEintgRsPgR = { "vector<int,allocator<int> >" , 99 , -1 };
G__linked_taginfo G__monaAnaDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<int,allocator<int> >::iterator>" , 99 , -1 };
G__linked_taginfo G__monaAnaDictLN_StMaterial = { "StMaterial" , 99 , -1 };
G__linked_taginfo G__monaAnaDictLN_vectorlEStElementcOallocatorlEStElementgRsPgR = { "vector<StElement,allocator<StElement> >" , 99 , -1 };
G__linked_taginfo G__monaAnaDictLN_reverse_iteratorlEvectorlEStElementcOallocatorlEStElementgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<StElement,allocator<StElement> >::iterator>" , 99 , -1 };
G__linked_taginfo G__monaAnaDictLN_vectorlEStReactionmUcOallocatorlEStReactionmUgRsPgR = { "vector<StReaction*,allocator<StReaction*> >" , 99 , -1 };
G__linked_taginfo G__monaAnaDictLN_reverse_iteratorlEvectorlEStReactionmUcOallocatorlEStReactionmUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<StReaction*,allocator<StReaction*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__monaAnaDictLN_setlEDatacOltDatacOallocatorlEDatagRsPgR = { "set<Data,ltData,allocator<Data> >" , 99 , -1 };
G__linked_taginfo G__monaAnaDictLN_StRageny = { "StRageny" , 99 , -1 };
G__linked_taginfo G__monaAnaDictLN_maplERagenyTargetBeamcOStInterpmUcOltRagenyTBcOallocatorlEpairlEconstsPRagenyTargetBeamcOStInterpmUgRsPgRsPgR = { "map<RagenyTargetBeam,StInterp*,ltRagenyTB,allocator<pair<const RagenyTargetBeam,StInterp*> > >" , 99 , -1 };
G__linked_taginfo G__monaAnaDictLN_CalMonaEvent = { "CalMonaEvent" , 99 , -1 };
G__linked_taginfo G__monaAnaDictLN_ParticleCoordinates = { "ParticleCoordinates" , 99 , -1 };
G__linked_taginfo G__monaAnaDictLN_MonaAnalyzedEvent = { "MonaAnalyzedEvent" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtablemonaAnaDict() {
  G__monaAnaDictLN_TClass.tagnum = -1 ;
  G__monaAnaDictLN_TBuffer.tagnum = -1 ;
  G__monaAnaDictLN_TMemberInspector.tagnum = -1 ;
  G__monaAnaDictLN_TObject.tagnum = -1 ;
  G__monaAnaDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__monaAnaDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__monaAnaDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G__monaAnaDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__monaAnaDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR.tagnum = -1 ;
  G__monaAnaDictLN_maplElongcOintcOlesslElonggRcOallocatorlEpairlEconstsPlongcOintgRsPgRsPgR.tagnum = -1 ;
  G__monaAnaDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR.tagnum = -1 ;
  G__monaAnaDictLN_TMatrixTBaselEfloatgR.tagnum = -1 ;
  G__monaAnaDictLN_TMatrixTBaselEdoublegR.tagnum = -1 ;
  G__monaAnaDictLN_TVectorTlEfloatgR.tagnum = -1 ;
  G__monaAnaDictLN_TVectorTlEdoublegR.tagnum = -1 ;
  G__monaAnaDictLN_TElementActionTlEfloatgR.tagnum = -1 ;
  G__monaAnaDictLN_TElementPosActionTlEfloatgR.tagnum = -1 ;
  G__monaAnaDictLN_TMatrixTlEfloatgR.tagnum = -1 ;
  G__monaAnaDictLN_TMatrixTRow_constlEfloatgR.tagnum = -1 ;
  G__monaAnaDictLN_TMatrixTRowlEfloatgR.tagnum = -1 ;
  G__monaAnaDictLN_TMatrixTDiag_constlEfloatgR.tagnum = -1 ;
  G__monaAnaDictLN_TMatrixTColumn_constlEfloatgR.tagnum = -1 ;
  G__monaAnaDictLN_TMatrixTFlat_constlEfloatgR.tagnum = -1 ;
  G__monaAnaDictLN_TMatrixTSub_constlEfloatgR.tagnum = -1 ;
  G__monaAnaDictLN_TMatrixTSparseRow_constlEfloatgR.tagnum = -1 ;
  G__monaAnaDictLN_TMatrixTSparseDiag_constlEfloatgR.tagnum = -1 ;
  G__monaAnaDictLN_TMatrixTColumnlEfloatgR.tagnum = -1 ;
  G__monaAnaDictLN_TMatrixTDiaglEfloatgR.tagnum = -1 ;
  G__monaAnaDictLN_TMatrixTFlatlEfloatgR.tagnum = -1 ;
  G__monaAnaDictLN_TMatrixTSublEfloatgR.tagnum = -1 ;
  G__monaAnaDictLN_TMatrixTSparseRowlEfloatgR.tagnum = -1 ;
  G__monaAnaDictLN_TMatrixTSparseDiaglEfloatgR.tagnum = -1 ;
  G__monaAnaDictLN_TVector3.tagnum = -1 ;
  G__monaAnaDictLN_TLorentzVector.tagnum = -1 ;
  G__monaAnaDictLN_CosyMap.tagnum = -1 ;
  G__monaAnaDictLN_vectorlECosyMapLinecOallocatorlECosyMapLinegRsPgR.tagnum = -1 ;
  G__monaAnaDictLN_reverse_iteratorlEvectorlECosyMapLinecOallocatorlECosyMapLinegRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__monaAnaDictLN_maplEintcOTGeoElementRNmUcOlesslEintgRcOallocatorlEpairlEconstsPintcOTGeoElementRNmUgRsPgRsPgR.tagnum = -1 ;
  G__monaAnaDictLN_vectorlETGeoVolumeAssemblycLcLThreadData_tmUcOallocatorlETGeoVolumeAssemblycLcLThreadData_tmUgRsPgR.tagnum = -1 ;
  G__monaAnaDictLN_reverse_iteratorlEvectorlETGeoVolumeAssemblycLcLThreadData_tmUcOallocatorlETGeoVolumeAssemblycLcLThreadData_tmUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__monaAnaDictLN_maplElongcOTGeoNavigatorArraymUcOlesslElonggRcOallocatorlEpairlEconstsPlongcOTGeoNavigatorArraymUgRsPgRsPgR.tagnum = -1 ;
  G__monaAnaDictLN_CycSrim.tagnum = -1 ;
  G__monaAnaDictLN_vectorlEStParticlecOallocatorlEStParticlegRsPgR.tagnum = -1 ;
  G__monaAnaDictLN_reverse_iteratorlEvectorlEStParticlecOallocatorlEStParticlegRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__monaAnaDictLN_vectorlEstringcOallocatorlEstringgRsPgR.tagnum = -1 ;
  G__monaAnaDictLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__monaAnaDictLN_vectorlEintcOallocatorlEintgRsPgR.tagnum = -1 ;
  G__monaAnaDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__monaAnaDictLN_StMaterial.tagnum = -1 ;
  G__monaAnaDictLN_vectorlEStElementcOallocatorlEStElementgRsPgR.tagnum = -1 ;
  G__monaAnaDictLN_reverse_iteratorlEvectorlEStElementcOallocatorlEStElementgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__monaAnaDictLN_vectorlEStReactionmUcOallocatorlEStReactionmUgRsPgR.tagnum = -1 ;
  G__monaAnaDictLN_reverse_iteratorlEvectorlEStReactionmUcOallocatorlEStReactionmUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__monaAnaDictLN_setlEDatacOltDatacOallocatorlEDatagRsPgR.tagnum = -1 ;
  G__monaAnaDictLN_StRageny.tagnum = -1 ;
  G__monaAnaDictLN_maplERagenyTargetBeamcOStInterpmUcOltRagenyTBcOallocatorlEpairlEconstsPRagenyTargetBeamcOStInterpmUgRsPgRsPgR.tagnum = -1 ;
  G__monaAnaDictLN_CalMonaEvent.tagnum = -1 ;
  G__monaAnaDictLN_ParticleCoordinates.tagnum = -1 ;
  G__monaAnaDictLN_MonaAnalyzedEvent.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtablemonaAnaDict() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__monaAnaDictLN_TClass);
   G__get_linked_tagnum_fwd(&G__monaAnaDictLN_TBuffer);
   G__get_linked_tagnum_fwd(&G__monaAnaDictLN_TMemberInspector);
   G__get_linked_tagnum_fwd(&G__monaAnaDictLN_TObject);
   G__get_linked_tagnum_fwd(&G__monaAnaDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__monaAnaDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__monaAnaDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G__monaAnaDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__monaAnaDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR);
   G__get_linked_tagnum_fwd(&G__monaAnaDictLN_maplElongcOintcOlesslElonggRcOallocatorlEpairlEconstsPlongcOintgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__monaAnaDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__monaAnaDictLN_TMatrixTBaselEfloatgR);
   G__get_linked_tagnum_fwd(&G__monaAnaDictLN_TMatrixTBaselEdoublegR);
   G__get_linked_tagnum_fwd(&G__monaAnaDictLN_TVectorTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__monaAnaDictLN_TVectorTlEdoublegR);
   G__get_linked_tagnum_fwd(&G__monaAnaDictLN_TElementActionTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__monaAnaDictLN_TElementPosActionTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__monaAnaDictLN_TMatrixTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__monaAnaDictLN_TMatrixTRow_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__monaAnaDictLN_TMatrixTRowlEfloatgR);
   G__get_linked_tagnum_fwd(&G__monaAnaDictLN_TMatrixTDiag_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__monaAnaDictLN_TMatrixTColumn_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__monaAnaDictLN_TMatrixTFlat_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__monaAnaDictLN_TMatrixTSub_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__monaAnaDictLN_TMatrixTSparseRow_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__monaAnaDictLN_TMatrixTSparseDiag_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__monaAnaDictLN_TMatrixTColumnlEfloatgR);
   G__get_linked_tagnum_fwd(&G__monaAnaDictLN_TMatrixTDiaglEfloatgR);
   G__get_linked_tagnum_fwd(&G__monaAnaDictLN_TMatrixTFlatlEfloatgR);
   G__get_linked_tagnum_fwd(&G__monaAnaDictLN_TMatrixTSublEfloatgR);
   G__get_linked_tagnum_fwd(&G__monaAnaDictLN_TMatrixTSparseRowlEfloatgR);
   G__get_linked_tagnum_fwd(&G__monaAnaDictLN_TMatrixTSparseDiaglEfloatgR);
   G__get_linked_tagnum_fwd(&G__monaAnaDictLN_TVector3);
   G__get_linked_tagnum_fwd(&G__monaAnaDictLN_TLorentzVector);
   G__get_linked_tagnum_fwd(&G__monaAnaDictLN_CosyMap);
   G__get_linked_tagnum_fwd(&G__monaAnaDictLN_vectorlECosyMapLinecOallocatorlECosyMapLinegRsPgR);
   G__get_linked_tagnum_fwd(&G__monaAnaDictLN_reverse_iteratorlEvectorlECosyMapLinecOallocatorlECosyMapLinegRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__monaAnaDictLN_maplEintcOTGeoElementRNmUcOlesslEintgRcOallocatorlEpairlEconstsPintcOTGeoElementRNmUgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__monaAnaDictLN_vectorlETGeoVolumeAssemblycLcLThreadData_tmUcOallocatorlETGeoVolumeAssemblycLcLThreadData_tmUgRsPgR);
   G__get_linked_tagnum_fwd(&G__monaAnaDictLN_reverse_iteratorlEvectorlETGeoVolumeAssemblycLcLThreadData_tmUcOallocatorlETGeoVolumeAssemblycLcLThreadData_tmUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__monaAnaDictLN_maplElongcOTGeoNavigatorArraymUcOlesslElonggRcOallocatorlEpairlEconstsPlongcOTGeoNavigatorArraymUgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__monaAnaDictLN_CycSrim);
   G__get_linked_tagnum_fwd(&G__monaAnaDictLN_vectorlEStParticlecOallocatorlEStParticlegRsPgR);
   G__get_linked_tagnum_fwd(&G__monaAnaDictLN_reverse_iteratorlEvectorlEStParticlecOallocatorlEStParticlegRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__monaAnaDictLN_vectorlEstringcOallocatorlEstringgRsPgR);
   G__get_linked_tagnum_fwd(&G__monaAnaDictLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__monaAnaDictLN_vectorlEintcOallocatorlEintgRsPgR);
   G__get_linked_tagnum_fwd(&G__monaAnaDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__monaAnaDictLN_StMaterial);
   G__get_linked_tagnum_fwd(&G__monaAnaDictLN_vectorlEStElementcOallocatorlEStElementgRsPgR);
   G__get_linked_tagnum_fwd(&G__monaAnaDictLN_reverse_iteratorlEvectorlEStElementcOallocatorlEStElementgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__monaAnaDictLN_vectorlEStReactionmUcOallocatorlEStReactionmUgRsPgR);
   G__get_linked_tagnum_fwd(&G__monaAnaDictLN_reverse_iteratorlEvectorlEStReactionmUcOallocatorlEStReactionmUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__monaAnaDictLN_setlEDatacOltDatacOallocatorlEDatagRsPgR);
   G__get_linked_tagnum_fwd(&G__monaAnaDictLN_StRageny);
   G__get_linked_tagnum_fwd(&G__monaAnaDictLN_maplERagenyTargetBeamcOStInterpmUcOltRagenyTBcOallocatorlEpairlEconstsPRagenyTargetBeamcOStInterpmUgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__monaAnaDictLN_CalMonaEvent);
   G__get_linked_tagnum_fwd(&G__monaAnaDictLN_ParticleCoordinates);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__monaAnaDictLN_MonaAnalyzedEvent),sizeof(MonaAnalyzedEvent),-1,28928,(char*)NULL,G__setup_memvarMonaAnalyzedEvent,G__setup_memfuncMonaAnalyzedEvent);
}
extern "C" void G__cpp_setupmonaAnaDict(void) {
  G__check_setup_version(30051515,"G__cpp_setupmonaAnaDict()");
  G__set_cpp_environmentmonaAnaDict();
  G__cpp_setup_tagtablemonaAnaDict();

  G__cpp_setup_inheritancemonaAnaDict();

  G__cpp_setup_typetablemonaAnaDict();

  G__cpp_setup_memvarmonaAnaDict();

  G__cpp_setup_memfuncmonaAnaDict();
  G__cpp_setup_globalmonaAnaDict();
  G__cpp_setup_funcmonaAnaDict();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncmonaAnaDict();
  return;
}
class G__cpp_setup_initmonaAnaDict {
  public:
    G__cpp_setup_initmonaAnaDict() { G__add_setup_func("monaAnaDict",(G__incsetup)(&G__cpp_setupmonaAnaDict)); G__call_setup_funcs(); }
   ~G__cpp_setup_initmonaAnaDict() { G__remove_setup_func("monaAnaDict"); }
};
G__cpp_setup_initmonaAnaDict G__cpp_setup_initializermonaAnaDict;

