#!/bin/bash
# Script to generate input files for use with MoNASIM_Scripts.
# Takes in a string as argument "var_name = var_value;" and writes it to file.
# If argument is not specified, it writes blank space.
# Blank space in an input file will not break ST_MoNA (it shouldn't!...)
# MDJ 8/9/13

# List of input variables
# VAR01 is treated as the file name
VAR01=$1    VAR02=$2    VAR03=$3    VAR04=$4    VAR05=$5    VAR06=$6    VAR07=$7    VAR08=$8    VAR09=$9    VAR10=${10}
VAR11=${11} VAR12=${12} VAR13=${13} VAR14=${14} VAR15=${15} VAR16=${16} VAR17=${17} VAR18=${18} VAR19=${19} VAR20=${20}
VAR21=${21} VAR22=${22} VAR23=${23} VAR24=${24} VAR25=${25} VAR26=${26} VAR27=${27} VAR28=${28} VAR29=${29} VAR30=${30}
VAR31=${31} VAR32=${32} VAR33=${33} VAR34=${34} VAR35=${35} VAR36=${36} VAR37=${37} VAR38=${38} VAR39=${39} VAR40=${40}
VAR41=${41} VAR42=${42} VAR43=${43} VAR44=${44} VAR45=${45} VAR46=${46} VAR47=${47} VAR48=${48} VAR49=${49} VAR50=${50}
VAR51=${51} VAR52=${52} VAR53=${53} VAR54=${54} VAR55=${55} VAR56=${56} VAR57=${57} VAR58=${58} VAR59=${59} VAR60=${60}


outfile="/projects/mona-sim/jonesm/st_mona/input_files/input_file_temp.txt"
outcopy="/projects/mona-sim/jonesm/st_mona/input_files/$VAR01" 

echo $outcopy 

#Array of variables, needs to be extended if you add more variables
declare -a arr=(         "$VAR02" "$VAR03" "$VAR04" "$VAR05" "$VAR06" "$VAR07" "$VAR08" "$VAR09" "$VAR10"
                "$VAR11" "$VAR12" "$VAR13" "$VAR14" "$VAR15" "$VAR16" "$VAR17" "$VAR18" "$VAR19" "$VAR20"
                "$VAR21" "$VAR22" "$VAR23" "$VAR24" "$VAR25" "$VAR26" "$VAR27" "$VAR28" "$VAR29" "$VAR30"
                "$VAR31" "$VAR32" "$VAR33" "$VAR34" "$VAR35" "$VAR36" "$VAR37" "$VAR38" "$VAR39" "$VAR40"
                "$VAR41" "$VAR42" "$VAR43" "$VAR44" "$VAR45" "$VAR46" "$VAR47" "$VAR48" "$VAR49" "$VAR50"
                "$VAR51" "$VAR52" "$VAR53" "$VAR54" "$VAR55" "$VAR56" "$VAR57" "$VAR58" "$VAR59" "$VAR60"             
                )
                

# create new file
echo -n  > $outfile 
echo -n  > $outcopy

echo -e "#Input File generated by write_input.sh for your sciencing convenience." >> $outfile
echo -e "#Copy Input File generated by write_input.sh for your sciencing convenience." >> $outcopy

# loop through array and write var names to files
for i in "${arr[@]}"
do
    echo -e "$i"  >> $outfile 
    echo -e "$i"  >> $outcopy
    
done
