/********************************************************************
* monaAnaDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error monaAnaDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#include "G__ci.h"
extern "C" {
extern void G__cpp_setup_tagtablemonaAnaDict();
extern void G__cpp_setup_inheritancemonaAnaDict();
extern void G__cpp_setup_typetablemonaAnaDict();
extern void G__cpp_setup_memvarmonaAnaDict();
extern void G__cpp_setup_globalmonaAnaDict();
extern void G__cpp_setup_memfuncmonaAnaDict();
extern void G__cpp_setup_funcmonaAnaDict();
extern void G__set_cpp_environmentmonaAnaDict();
}


#include "TROOT.h"
#include "TMemberInspector.h"
#include "mona_analysis.hh"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__monaAnaDictLN_TClass;
extern G__linked_taginfo G__monaAnaDictLN_TBuffer;
extern G__linked_taginfo G__monaAnaDictLN_TMemberInspector;
extern G__linked_taginfo G__monaAnaDictLN_TObject;
extern G__linked_taginfo G__monaAnaDictLN_vectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgR;
extern G__linked_taginfo G__monaAnaDictLN_reverse_iteratorlEvectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__monaAnaDictLN_multimaplEvoidmUcOshortcOlesslEvoidmUgRcOallocatorlEpairlEvoidmUsPconstcOshortgRsPgRsPgR;
extern G__linked_taginfo G__monaAnaDictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__monaAnaDictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__monaAnaDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__monaAnaDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__monaAnaDictLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__monaAnaDictLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__monaAnaDictLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__monaAnaDictLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__monaAnaDictLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__monaAnaDictLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__monaAnaDictLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__monaAnaDictLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__monaAnaDictLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__monaAnaDictLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__monaAnaDictLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__monaAnaDictLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__monaAnaDictLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__monaAnaDictLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__monaAnaDictLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__monaAnaDictLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__monaAnaDictLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__monaAnaDictLN_TVector3;
extern G__linked_taginfo G__monaAnaDictLN_TLorentzVector;
extern G__linked_taginfo G__monaAnaDictLN_CosyMap;
extern G__linked_taginfo G__monaAnaDictLN_vectorlECosyMapLinecOallocatorlECosyMapLinegRsPgR;
extern G__linked_taginfo G__monaAnaDictLN_reverse_iteratorlEvectorlECosyMapLinecOallocatorlECosyMapLinegRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__monaAnaDictLN_vectorlEStParticlecOallocatorlEStParticlegRsPgR;
extern G__linked_taginfo G__monaAnaDictLN_reverse_iteratorlEvectorlEStParticlecOallocatorlEStParticlegRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__monaAnaDictLN_vectorlEstringcOallocatorlEstringgRsPgR;
extern G__linked_taginfo G__monaAnaDictLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__monaAnaDictLN_StMaterial;
extern G__linked_taginfo G__monaAnaDictLN_vectorlEStElementcOallocatorlEStElementgRsPgR;
extern G__linked_taginfo G__monaAnaDictLN_reverse_iteratorlEvectorlEStElementcOallocatorlEStElementgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__monaAnaDictLN_vectorlEStReactionmUcOallocatorlEStReactionmUgRsPgR;
extern G__linked_taginfo G__monaAnaDictLN_reverse_iteratorlEvectorlEStReactionmUcOallocatorlEStReactionmUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__monaAnaDictLN_setlEDatacOltDatacOallocatorlEDatagRsPgR;
extern G__linked_taginfo G__monaAnaDictLN_StRageny;
extern G__linked_taginfo G__monaAnaDictLN_maplERagenyTargetBeamcOStInterpmUcOltRagenyTBcOallocatorlEpairlEconstsPRagenyTargetBeamcOStInterpmUgRsPgRsPgR;
extern G__linked_taginfo G__monaAnaDictLN_CalMonaEvent;
extern G__linked_taginfo G__monaAnaDictLN_ParticleCoordinates;
extern G__linked_taginfo G__monaAnaDictLN_MonaAnalyzedEvent;

/* STUB derived class for protected member access */
